// sections/registry.ts — what the editor is allowed to change, per section type.
//
// THE REGISTRY LIVES IN CODE, NOT IN THE DATABASE. It has to version-lock with
// the components that render it: a field the desk offers but the component does
// not read is a promise the page cannot keep, and the only way to keep those in
// step is to ship them together.
//
// Every `max` is derived from the CSS of the component that renders the field —
// the clamp() font size, the container width in ch, the number of lines the
// design allows, the padding of a chamfered pill. A limit without such a
// derivation is a guess, and a guess here means either a wrapped button or a
// ceiling nobody can reach.

import type { SectionType } from "./schema";

// CHANGED — replaces the existing HOME_HERO: the ring-loop film retired with
// the round-2 hero (2026-08-12, DESIGN-DIRECTION «hero חם סטטי») —
// poster/filmWebm/filmMp4 dropped with it, and the dead ctaSub + scrollCue
// left too (the «שיחת היכרות חינם» sub-line and the «גללי» cue came off the
// render). +imageAlt: the description of the static REAL photograph (cl-115,
// protein pancakes) — the path stays a constant in page.tsx, the same
// contract as the guide portrait. The film assets stay on disk.
export const HOME_HERO: SectionType = {
  type: "home-hero",
  label: "פתיח — הפריסה החמה",
  purpose: "הרגע הראשון: פריסת מגזין — המילים על הנייר, צילום אמיתי מהמטבח לצידן, והכפתור הראשי.",
  required: true,
  pin: "start",
  fields: [
    {
      key: "kicker",
      label: "שורת פתיחה קטנה",
      kind: "text",
      required: true,
      max: 48,
      // text-xs font-bold tracking-eyebrow ≈ 9px/char in the words column
      // (max-w-[700px]), minus the ◆ glyph and its gap. 48 keeps it to two
      // lines at 390px.
      hint: "היהלום מצויר בקוד, אין צורך להקליד אותו",
    },
    {
      key: "title",
      label: "כותרת ראשית",
      kind: "textarea",
      required: true,
      lines: 2,
      maxPerLine: 24,
      max: 50,
      // RevealHeading splits on \n ONLY and gives each line its own mask.
      // clamp(2.4rem,4.5vw,4rem) → 64px cap in the split column's max-w-[700px]
      // ≈ 24 chars a line — the design pass pinned 4.5vw/4rem as the largest
      // size that keeps each written line whole from 1024px up, so the current
      // lines sit exactly at the cap. A longer line wraps INSIDE its mask and
      // the reveal stutters.
      hint: "שתי שורות. שורה ארוכה מדי תישבר באמצע האנימציה",
    },
    {
      key: "titleAccent",
      label: "המילים עם הקו הוורוד",
      kind: "mark",
      of: "title",
      max: 20,
      hint: "חייב להיות רצף מילים מתוך שורה אחת של הכותרת",
    },
    {
      key: "lede",
      label: "פסקת הפתיחה",
      kind: "textarea",
      required: true,
      max: 140,
      // max-w-[48ch] text-xl leading-[1.65] → 48 chars a line, 3 lines before
      // it pushes the button below the fold on a phone.
    },
    {
      key: "ctaPrimary",
      label: "כפתור ראשי",
      kind: "text",
      required: true,
      max: 18,
      // btn-chamfer px-9 py-4 text-base font-bold. The clipped corner breaks if
      // the label wraps, so this one really is a single line.
      hint: "שורה אחת. טקסט ארוך ישבור את הפינה החתוכה של הכפתור",
    },
    {
      key: "trustToken",
      label: "תג האמון",
      kind: "text",
      required: true,
      max: 34,
      // text-[13px] font-bold tracking-eyebrow — a hairline masthead row now,
      // not a pill: it shares the ruled border-t line with the recipes link
      // (flex-wrap), so one line here keeps the row a masthead.
    },
    {
      key: "trustTokenLicense",
      label: "סיפא הרישיון",
      kind: "text",
      max: 32,
      hint: "מוצג רק ממסך 640 פיקסל ומעלה, ולכן מתחיל במפריד ‎ · ‎",
    },
    { key: "ctaRecipes", label: "קישור משני למתכונים", kind: "text", max: 60 },
    {
      key: "imageAlt",
      label: "תיאור צילום הפתיח (alt)",
      kind: "text",
      required: true,
      max: 110,
      // the REAL hero photograph (cl-115) fills the 9fr column at near-native
      // ratio; the photo path is art direction and stays a constant in
      // page.tsx — only its description is hers. 110 = the house alt ceiling
      // (same as home-guide portraitAlt).
      hint: "מנה אמיתית מהמטבח שלה בלבד. לתאר מה רואים, בלי \"תמונה של\"",
    },
  ],
};

export const CONTACT_DOOR: SectionType = {
  type: "contact-door",
  label: "הדלת השקטה — פתיח",
  purpose: "הרגע הראשון בעמוד: ההזמנה לשיחה, ההבטחה, והכפתור הראשי.",
  required: true,
  pin: "start",
  fields: [
      { key: "crumb",
        label: "שם העמוד בשביל הפירורים",
        kind: "text",
        required: true,
        max: 20,
        hint: "זהה לתווית בתפריט העליון (nav ב-site.ts) — שינוי כאן לא משנה את התפריט" },
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 38,
        hint: "היהלום מצויר בקוד, אין צורך להקליד אותו" },
      { key: "title",
        label: "כותרת ראשית",
        kind: "text",
        required: true,
        max: 26,
        hint: "שורה אחת. RevealHeading חותך על \\n — שורה שנשברת בתוך המסכה מגמגמת באנימציה" },
      { key: "body",
        label: "פסקת ההזמנה",
        kind: "textarea",
        required: true,
        max: 200 },
      { key: "bodyAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "body",
        hint: "חייב להיות רצף מילים מתוך פסקת ההזמנה" },
      { key: "cta",
        label: "כפתור ראשי",
        kind: "text",
        required: true,
        max: 22,
        hint: "שורה אחת. טקסט ארוך ישבור את הפינה החתוכה של הכפתור" },
      { key: "ctaSub",
        label: "שורה מתחת לכפתור",
        kind: "text",
        max: 28 },
      { key: "promise",
        label: "הבטחת הזמן",
        kind: "text",
        required: true,
        max: 44,
        hint: "אותה הבטחה חוזרת גם בסקשן הטופס וגם בסקשן «איפה נפגשות» — שינוי כאן לא מחיל את עצמו עליהן" },
      { key: "place",
        label: "שורת המקום",
        kind: "text",
        required: true,
        max: 40 },
      { key: "trustToken",
        label: "שורת הרישיון",
        kind: "text",
        required: true,
        max: 52,
        hint: "שורה שקטה מתחת לגלולה — לא גלולה מתחרה" }
  ],
};

export const CONTACT_LEAD: SectionType = {
  type: "contact-lead",
  label: "רצפת-החיכוך — כרטיס הטופס",
  purpose: "הדבר החשוב בעמוד: הכותרת, ההסבר על החבילות, טופס ≤5 שדות, וואטסאפ ומסך-תודה.",
  required: true,
  fields: [
      { key: "title",
        label: "כותרת הכרטיס",
        kind: "textarea",
        required: true,
        max: 48,
        hint: "שתי שורות לכל היותר — הכותרת יושבת בתוך מסכת-חשיפה אחת" },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 16,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך הכותרת" },
      { key: "body",
        label: "פסקת ההסבר",
        kind: "textarea",
        required: true,
        max: 140 },
      { key: "packages",
        label: "פסקת החבילות",
        kind: "textarea",
        max: 160,
        hint: "בלי מחירים — ההכרעה היא שהמחיר נאמר בשיחה" },
      { key: "nameLabel",
        label: "תווית: שם",
        kind: "text",
        required: true,
        max: 24 },
      { key: "phoneLabel",
        label: "תווית: טלפון",
        kind: "text",
        required: true,
        max: 28 },
      { key: "messageLabel",
        label: "תווית: הודעה",
        kind: "text",
        max: 44,
        hint: "שדה לא חובה — «(לא חובה)» הוא חלק מהתווית, אין תג נפרד" },
      { key: "emailLabel",
        label: "תווית: אימייל",
        kind: "text",
        required: true,
        max: 20,
        hint: "משמשת גם כתווית השדה וגם ככיתוב של כפתור «+ אימייל» שפותח אותו" },
      { key: "consentLabel",
        label: "שורת ההסכמה",
        kind: "textarea",
        required: true,
        max: 70,
        hint: "חובה משפטית — חייבת לתאר את הערוצים שבהם יוצרים קשר" },
      { key: "submitLabel",
        label: "כפתור שליחה",
        kind: "text",
        required: true,
        max: 28,
        hint: "שורה אחת. זה הכפתור הכי חשוב באתר" },
      { key: "submittingLabel",
        label: "תווית בזמן שליחה",
        kind: "text",
        max: 16,
        locked: true,
        hint: "מחרוזת-מערכת, זהה לטופס הכללי (ContactLeadForm) — נעולה כדי ששני הטפסים לא ייפרדו" },
      { key: "whatsappLabel",
        label: "שורת הוואטסאפ",
        kind: "text",
        required: true,
        max: 44,
        hint: "מספר הטלפון לעולם לא מודפס — רק הקישור לוואטסאפ" },
      { key: "thanks",
        label: "מסך-תודה: המשפט",
        kind: "textarea",
        required: true,
        max: 140,
        hint: "משחזר את ההבטחה — הלקוחה קוראת אותו מיד אחרי השליחה" },
      { key: "thanksLink",
        label: "המילים שהופכות לקישור",
        kind: "mark",
        max: 24,
        of: "thanks",
        hint: "רצף מילים מתוך משפט התודה — היעד (/מתכונים) קבוע בקוד" },
      { key: "promise",
        label: "הבטחת הזמן",
        kind: "text",
        required: true,
        max: 44,
        hint: "אותה הבטחה מופיעה גם בפתיח וגם בסקשן «איפה נפגשות»" },
      { key: "place",
        label: "שורת המקום",
        kind: "text",
        required: true,
        max: 48 },
      { key: "trustToken",
        label: "שורת הרישיון",
        kind: "text",
        required: true,
        max: 56 }
  ],
};

export const CONTACT_WHERE: SectionType = {
  type: "contact-where",
  label: "איפה נפגשות",
  purpose: "שלוש הדרכים האמיתיות להיפגש: אונליין, קליניקה ברעננה, וואטסאפ בין הפגישות — ושורת המעקב, הדרך הרביעית שלא מבקשת כלום.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 38 },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "textarea",
        required: true,
        max: 74,
        lines: 2,
        maxPerLine: 36,
        hint: "שתי שורות, מופרדות ב-Enter. כל שורה מקבלת מסכת-חשיפה משלה" },
      { key: "body",
        label: "פסקת ההסבר",
        kind: "textarea",
        required: true,
        max: 190 },
      { key: "items",
        label: "הדרכים להיפגש",
        kind: "repeater",
        required: true,
        itemLabel: "דרך",
        min: 1,
        fields: [
          { key: "title",
            label: "כותרת הדרך",
            kind: "text",
            required: true,
            max: 34,
            hint: "הקו הוורוד נמשך על כל הכותרת, ולכן אין כאן שדה-סימון נפרד" },
          { key: "body",
            label: "תיאור הדרך",
            kind: "text",
            required: true,
            max: 90 }
        ] },
      { key: "chip",
        label: "גלולת ההבטחה",
        kind: "text",
        required: true,
        max: 44,
        hint: "אותה הבטחה שמופיעה בפתיח ובכרטיס הטופס" },
      { key: "socialLabel",
        label: "כותרת שורת המעקב",
        kind: "text",
        max: 40,
        // SocialLinks renders it mb-3 text-sm font-bold inside the sand card
        // (p-7 below md) — at 390px the card's inner line is ~300px, and 14px
        // bold Hebrew ≈ 7.5px/char, so 40 keeps the heading to one quiet line
        // on a phone.
        hint: "הכותרת מעל צ'יפי אינסטגרם/טיקטוק. הפרופילים עצמם מנוהלים בהגדרות — כאן רק המילים; ריקון השדה משמיט את הכותרת והצ'יפים נשארים" }
  ],
};

export const ABOUT_HERO: SectionType = {
  type: "about-hero",
  label: "פתיח — נעים להכיר",
  purpose: "הרגע הראשון של העמוד: השם, הרישיון, משבצת הפורטרט והכפתור לשיחה.",
  required: true,
  pin: "start",
  fields: [
      { key: "crumbLabel",
        label: "שם העמוד בשביל הניווט",
        kind: "text",
        required: true,
        max: 18,
        hint: "הפירור «בית» נוסף אוטומטית בקוד" },
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 48,
        hint: "היהלום מצויר בקוד, אין צורך להקליד אותו" },
      { key: "title",
        label: "השם (הכותרת הראשית)",
        kind: "text",
        required: true,
        max: 20,
        hint: "שורה אחת. איות מחייב: אקרלינג, לא אקרלינק" },
      { key: "lede",
        label: "פסקת הפתיחה",
        kind: "textarea",
        required: true,
        max: 156,
        hint: "זו גם תיאור העמוד למנועי חיפוש (meta description)" },
      { key: "licenseChip",
        label: "תג הרישיון",
        kind: "text",
        required: true,
        max: 64,
        hint: "שורה אחת. זו הצהרה רגולטורית, לשנות רק מול התעודה" },
      { key: "ctaPrimary",
        label: "כפתור ראשי",
        kind: "text",
        required: true,
        max: 18,
        hint: "שורה אחת. טקסט ארוך ישבור את הפינה החתוכה של הכפתור" },
      { key: "ctaPrimarySub",
        label: "שורה מתחת לכפתור",
        kind: "text",
        max: 28,
        hint: "מתחברת בקוד לשורה אחת עם השורה הקטנה, עם ‎ · ‎ באמצע" },
      { key: "ctaMicro",
        label: "השורה הקטנה שאחריה",
        kind: "text",
        max: 38,
        hint: "מתחברת בקוד לשורה אחת עם השורה שמתחת לכפתור" },
      { key: "ctaSecondary",
        label: "קישור משני אל הסיפור",
        kind: "text",
        max: 30,
        hint: "החץ ↓ הוא חלק מהטקסט" },
      { key: "portraitLabel",
        label: "תיאור הפורטרט (alt)",
        kind: "text",
        max: 110,
        hint: "לא מוצג היום. שמור לרגע שבו יגיע פורטרט אמיתי 4:5. פורטרט אמיתי בלבד, לעולם לא תמונה מיוצרת" },
      { key: "portraitSignature",
        label: "החתימה בכרטיס-הביקור",
        kind: "text",
        max: 10,
        hint: "השם הפרטי בכתב-יד. אותו ערך שמופיע גם בסוף המכתב" },
      { key: "portraitRole",
        label: "התפקיד בכרטיס-הביקור",
        kind: "text",
        max: 40,
        hint: "אותו נוסח כמו כותרת התעודה בסקשן ההסמכות" }
  ],
};

export const ABOUT_STORY: SectionType = {
  type: "about-story",
  label: "הסיפור שלי — המכתב החתום",
  purpose: "סיפור-המקור כמכתב אישי חתום, על רקע מנה אמיתית מהמטבח.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסיפור",
        kind: "textarea",
        required: true,
        max: 48,
        lines: 2,
        maxPerLine: 23,
        hint: "שתי שורות. שורה ארוכה מדי תישבר באמצע האנימציה" },
      { key: "p1",
        label: "פסקה ראשונה",
        kind: "textarea",
        required: true,
        max: 200 },
      { key: "p2",
        label: "פסקה שנייה",
        kind: "textarea",
        required: true,
        max: 200 },
      { key: "credo1",
        label: "האני-מאמין, משפט ראשון",
        kind: "textarea",
        required: true,
        max: 120 },
      { key: "credo2",
        label: "האני-מאמין, משפט שני",
        kind: "textarea",
        required: true,
        max: 120,
        hint: "המילה עם הקו הוורוד חייבת להופיע כאן ככתבה" },
      { key: "credo2Accent",
        label: "המילה עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "credo2",
        hint: "חייב להיות רצף מילים מתוך המשפט השני, בשורה אחת. אין התאמה — הקו פשוט לא יצויר" },
      { key: "signOff",
        label: "שורת הסיום",
        kind: "text",
        max: 60 },
      { key: "signature",
        label: "החתימה",
        kind: "text",
        max: 12 },
      { key: "image",
        label: "תמונת המנה שברקע",
        kind: "image",
        ratio: "3:4",
        hint: "מוצגת פעמיים: כעמודה גבוהה בצד במסך רחב, וכרצועה 3:2 בראש העמוד בנייד. תמונה לאורך תעבוד בשתיהן. מנה אמיתית מהמטבח שלה בלבד" },
      { key: "imageAlt",
        label: "תיאור התמונה (alt)",
        kind: "text",
        required: true,
        max: 110,
        hint: "מתאר את הרצועה בנייד. העותק במסך רחב הוא דקורטיבי ומקבל alt ריק" }
  ],
};

// NEW type — the professional standard that replaced the age answer (§19).
export const ABOUT_STANDARD: SectionType = {
  type: "about-standard",
  label: "הסטנדרט המקצועי — שלושת העקרונות",
  purpose: "הטיעון מהשיטה (החליף את תשובת-הגיל): תחום פרוץ, שלושה עקרונות שווים, ותחומי הליווי.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40,
        hint: "היהלום מצויר בקוד, אין צורך להקליד אותו" },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "textarea",
        required: true,
        // SplitText at var(--text-section) — clamp(1.7rem,4.4vw,3.25rem) → 52px
        // cap — inside the mx-auto max-w-[760px] column ≈ 32 chars a line; a
        // longer line wraps INSIDE its own reveal mask and the ink-wipe stutters.
        max: 66,
        lines: 2,
        maxPerLine: 32,
        hint: "שתי שורות, מופרדות ב-Enter. שורה ארוכה מדי תישבר באמצע האנימציה" },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך שורה אחת של הכותרת בדיוק, אחרת הקו פשוט לא יצויר" },
      { key: "body",
        label: "פסקת הטיעון",
        kind: "textarea",
        required: true,
        // text-lg leading-[1.75] in the same max-w-[760px] measure ≈ 90 chars a
        // line → four lines before the argument reads as a wall.
        max: 360 },
      { key: "principles",
        label: "שלושת העקרונות",
        kind: "repeater",
        required: true,
        itemLabel: "עיקרון",
        min: 3,
        max: 3,
        fields: [
          { key: "t",
            label: "כותרת העיקרון",
            kind: "text",
            required: true,
            // a grid column is (max-w-[1000px] − 2×gap-5)/3 ≈ 320px minus the
            // card's p-6 → ~272px; font-serif text-lg font-black ≈ 8px/char →
            // one line ≈ 34. leading-snug still holds a wrapped second line.
            max: 34 },
          { key: "d",
            label: "גוף העיקרון",
            kind: "textarea",
            required: true,
            // text-sm leading-relaxed in the same ~272px card ≈ 42 chars a line —
            // four lines before the three cards stop reading as peers.
            max: 170 }
        ],
        hint: "שלושה בדיוק — הרשת היא sm:grid-cols-3, רביעי יישבר לשורה משלו" },
      { key: "areasLabel",
        label: "כותרת רצועת התחומים",
        kind: "text",
        required: true,
        // text-[13px] font-bold tracking-eyebrow beside the ◆, one line inside
        // the sand band's p-7 at the 1000px measure.
        max: 30 },
      { key: "areas",
        label: "תחומי הליווי",
        kind: "repeater",
        required: true,
        itemLabel: "תחום",
        min: 1,
        fields: [
          { key: "",
            label: "שם התחום",
            kind: "text",
            required: true,
            // rounded-full border px-4 py-2 text-sm — a pill; a name that wraps
            // stops being a pill, so one line ≈ 30 at ~6.5px/char.
            max: 30 }
        ],
        hint: "צ'יפים בשורה נגללת (flex-wrap) — הסדר הוא סדר התצוגה" }
  ],
};

// NEW type — «הדרך לכאן» (2026-08-12): the personal essay that replaced the
// credentials wall (the ledger duplicated the standard's argument). The
// checkable records close the essay as a quiet ruled ledger.
export const ABOUT_ROAD: SectionType = {
  type: "about-road",
  label: "הדרך לכאן — הכתיבה האישית",
  purpose: "הסיפור מאחורי הבחירה במקצוע, בקולה, עם סרגל הרשומות הניתנות לבדיקה בסופו.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40,
        hint: "היהלום מצויר בקוד" },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "textarea",
        required: true,
        // SectionHeading's SplitText at the same 760px prose measure as the
        // standard above it — two lines, ~32 chars each before a written line
        // wraps inside its own reveal mask.
        max: 66,
        lines: 2,
        maxPerLine: 32,
        hint: "שתי שורות, מופרדות ב-Enter" },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        of: "title",
        max: 20,
        hint: "חייב להיות רצף מילים מתוך שורה אחת של הכותרת. אין התאמה — הקו פשוט לא יצויר" },
      { key: "p1",
        label: "פסקה ראשונה — איך זה התחיל",
        kind: "textarea",
        required: true,
        // text-lg leading-[1.75] in the 760px measure ≈ 90 chars a line —
        // three lines per paragraph keeps the essay an essay.
        max: 280 },
      { key: "p2",
        label: "פסקה שנייה — הדרך ללימודים",
        kind: "textarea",
        required: true,
        max: 280,
        hint: "העובדות כאן (תואר, התמחות, רישיון) חוזרות בסרגל הרשומות — לשנות יחד" },
      { key: "p3",
        label: "פסקה שלישית — למה המקצוע הזה",
        kind: "textarea",
        required: true,
        max: 280 },
      { key: "roleLine",
        label: "שורת התפקיד",
        kind: "text",
        required: true,
        max: 40,
        hint: "מופיעה גם מתחת לחתימה על כרטיס הפורטרט בפתיח" },
      { key: "recordsLabel",
        label: "כותרת סרגל הרשומות",
        kind: "text",
        required: true,
        max: 24 },
      { key: "records",
        label: "הרשומות",
        kind: "repeater",
        required: true,
        itemLabel: "רשומה",
        min: 1,
        max: 6,
        fields: [
          { key: "",
            label: "שורת הרשומה",
            kind: "text",
            required: true,
            // one ruled ledger row: text-[13px] tracking-eyebrow beside the
            // rose dash in the 760px measure — one line ≈ 64 chars.
            max: 64,
            hint: "נתונים רגולטוריים ולימודיים. לשנות רק מול תעודה — לעולם לא כותרת מומחיות" }
        ],
        hint: "כל רשומה שורה אחת בפנקס; הסדר הוא סדר התצוגה" },
      { key: "bridge",
        label: "שורת הסגירה",
        kind: "textarea",
        required: true,
        max: 180,
        hint: "המחשבה שלה על התהליך — מובילה אל הכפתור שמתחתיה" },
      { key: "bridgeCta",
        label: "קישור הפעולה",
        kind: "text",
        required: true,
        max: 44,
        hint: "החץ ← הוא חלק מהטקסט. היעד קבוע בקוד (/contact)" }
  ],
};

// CHANGED — replaces the existing ABOUT_CTA: +socialLabel (the sceptic's
// watch-first off-ramp above the social chips row).
export const ABOUT_CTA: SectionType = {
  type: "about-cta",
  label: "סגירה — הצעד שלך",
  purpose: "ההזמנה לשיחה בלי לחץ, עם דלת צדדית למתכונים ולרשתות.",
  required: true,
  pin: "end",
  fields: [
      { key: "promise",
        label: "הבטחת המענה",
        kind: "text",
        required: true,
        max: 60,
        hint: "מספר ימי העסקים חייב להיות אמיתי — זו הבטחה, לא סלוגן" },
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסגירה",
        kind: "textarea",
        required: true,
        max: 70,
        lines: 2,
        maxPerLine: 46,
        hint: "שתי שורות. השורה השנייה כבר על הגבול — כל תוספת תעטוף גם במסך רחב" },
      { key: "body",
        label: "פסקת הסגירה",
        kind: "textarea",
        required: true,
        max: 260 },
      { key: "recipes",
        label: "קישור צדדי למתכונים",
        kind: "text",
        max: 56,
        hint: "החץ ← הוא חלק מהטקסט" },
      { key: "socialLabel",
        label: "הכותרת מעל צ'יפי הרשתות",
        kind: "text",
        max: 40,
        // SocialLinks label: mb-3 text-sm font-bold — one quiet line above the
        // chips row inside the 880px spotlight card.
        hint: "הפרופילים עצמם (אינסטגרם/טיקטוק) מנוהלים בהגדרות האתר, לא כאן" },
      { key: "trustToken",
        label: "תג האמון",
        kind: "text",
        required: true,
        max: 64,
        hint: "הצהרה רגולטורית. לשנות רק מול התעודה" },
      { key: "button",
        label: "כפתור ראשי",
        kind: "text",
        required: true,
        max: 30,
        hint: "שורה אחת. טקסט ארוך ישבור את הפינה החתוכה של הכפתור" },
      { key: "signature",
        label: "החתימה",
        kind: "text",
        max: 12 }
  ],
};

export const PAGE_META: SectionType = {
  type: "page-meta",
  label: "כותרת ותיאור לגוגל",
  purpose: "מה שגוגל ומנועי-התשובות רואים, ושם השירות ב-Schema.",
  required: true,
  pin: "start",
  fields: [
      { key: "title",
        label: "כותרת העמוד בגוגל",
        kind: "text",
        required: true,
        max: 42,
        hint: "מופיע גם בלשונית הדפדפן; \"| אלונה אקרלינג\" מתווסף אוטומטית" },
      { key: "serviceName",
        label: "שם השירות בנתוני-Schema",
        kind: "text",
        max: 60,
        hint: "לא נראה לגולשת — זה מה שגוגל קורא כשם השירות" },
      { key: "serviceType",
        label: "סוג השירות בנתוני-Schema",
        kind: "text",
        max: 60,
        hint: "היום זהה לשם השירות" }
  ],
};

export const COACHING_HERO: SectionType = {
  type: "coaching-hero",
  label: "פתיח — שולחן הייעוץ",
  purpose: "הרגע הראשון: ההבטחה, תג האמון, ושני הכפתורים.",
  required: true,
  pin: "start",
  fields: [
      { key: "breadcrumb",
        label: "שם העמוד בשביל-הפירורים",
        kind: "text",
        required: true,
        max: 40,
        hint: "בדרך כלל זהה לכותרת העמוד בגוגל; מוזן גם ל-BreadcrumbList" },
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40,
        hint: "היהלום מצויר בקוד, אין צורך להקליד אותו" },
      { key: "title",
        label: "כותרת ראשית",
        kind: "text",
        required: true,
        max: 24,
        hint: "שורה אחת. אפשר לשבור עם Enter, אבל כל שורה מוגבלת ל-24 — שורה ארוכה יותר נשברת בתוך מסכת האנימציה" },
      { key: "body",
        label: "פסקת הפתיחה",
        kind: "textarea",
        required: true,
        max: 160,
        hint: "זו גם הפסקה שמופיעה בגוגל מתחת לכותרת — לכן עד 160 תווים" },
      { key: "trustToken",
        label: "תג האמון",
        kind: "text",
        required: true,
        max: 76,
        hint: "מתחת ל-640px מותר לה להישבר לשתי שורות; מ-640px ומעלה חייבת שורה אחת" },
      { key: "ctaPrimary",
        label: "כפתור ראשי",
        kind: "text",
        required: true,
        max: 20,
        hint: "שורה אחת. טקסט ארוך ישבור את הפינה החתוכה" },
      { key: "ctaSub",
        label: "שורה מתחת לכפתור",
        kind: "text",
        max: 24 },
      { key: "ctaWhatsapp",
        label: "כפתור וואטסאפ",
        kind: "text",
        max: 32,
        hint: "שורה אחת. הקישור עצמו לוואטסאפ נקבע בהגדרות" },
      { key: "micro",
        label: "שורת ההרגעה מתחת לכפתורים",
        kind: "text",
        max: 90,
        hint: "הנקודות המפרידות (·) הן חלק מהטקסט ונכתבות ידנית" }
  ],
};

export const COACHING_PROBLEM: SectionType = {
  type: "coaching-problem",
  label: "למה דווקא ליווי — הפער",
  purpose: "הרגע שבו נאמר שהפער הוא ה\"לבד\", לא הידע.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40,
        hint: "היהלום מצויר בקוד" },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 30,
        hint: "שורה אחת. הסקשן צר (עמודת קריאה) ולכן התקרה נמוכה מזו של סקשן רחב" },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך הכותרת בדיוק, אחרת הקו פשוט לא יצויר" },
      { key: "lead",
        label: "שורת המשנה",
        kind: "text",
        max: 120,
        hint: "בקוד השדה נקרא subtitle אך מוזן ל-prop בשם lead" },
      { key: "body1",
        label: "פסקה ראשונה",
        kind: "textarea",
        required: true,
        max: 220 },
      { key: "quote",
        label: "הציטוט הגדול",
        kind: "text",
        required: true,
        max: 100,
        hint: "משפט אחד וחזק. הוא נקודת המנוחה של העמוד, לא עוד פסקה" },
      { key: "quoteAccent",
        label: "המילה המודגשת בציטוט",
        kind: "mark",
        max: 12,
        of: "quote",
        hint: "בדרך כלל מילה אחת. חייבת להופיע בציטוט בדיוק" },
      { key: "body2",
        label: "פסקה שנייה",
        kind: "textarea",
        required: true,
        max: 220 },
      { key: "cta",
        label: "קישור לסקשן השיטה",
        kind: "text",
        max: 60,
        hint: "החץ ← הוא חלק מהטקסט ונכתב ידנית" }
  ],
};

export const COACHING_METHOD: SectionType = {
  type: "coaching-method",
  label: "השיטה — ארבעת העמודים",
  purpose: "ארבע הטענות שהופכות ידע לתוצאה; זה הרגע הנעוץ היחיד בעמוד.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 50,
        hint: "שורה אחת" },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך הכותרת בדיוק" },
      { key: "pillars",
        label: "עמודי השיטה",
        kind: "repeater",
        required: true,
        itemLabel: "עמוד",
        min: 2,
        fields: [
          { key: "title",
            label: "כותרת העמוד",
            kind: "text",
            required: true,
            max: 38,
            hint: "שורה אחת. הספרה הרפאים עולה מאחורי הכותרת בלבד" },
          { key: "body",
            label: "גוף העמוד",
            kind: "textarea",
            required: true,
            max: 280,
            hint: "עד שבע שורות. גוף ארוך יותר יגלוש מהכרטיס בחפיסה הנעוצה" }
        ],
        hint: "סדר הכרטיסים הוא סדר החלוקה בחפיסה; המספור נוצר אוטומטית" },
      { key: "cta",
        label: "קישור לחבילות",
        kind: "text",
        max: 60,
        hint: "החץ ← הוא חלק מהטקסט" }
  ],
};

export const COACHING_PACKAGES: SectionType = {
  type: "coaching-packages",
  label: "שלוש החבילות",
  purpose: "שלוש דרכי הכניסה לליווי, בלי מחיר, זו לצד זו להשוואה.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40,
        hint: "משמש גם כשם קטלוג ההצעות בנתוני ה-Schema של העמוד" },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 50 },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך הכותרת בדיוק" },
      { key: "lead",
        label: "פסקת ההסבר",
        kind: "textarea",
        max: 180 },
      { key: "facts",
        label: "רצועת העובדות",
        kind: "repeater",
        itemLabel: "עובדה",
        min: 0,
        fields: [
          { key: "text",
            label: "טקסט העובדה",
            kind: "text",
            max: 28 }
        ],
        hint: "שים לב: הטקסטים כאן משכפלים ידנית שמות חבילות ואת שורת ההרגעה בפתיח — עדכון שם חבילה לא יעדכן אותם" },
      { key: "fitLabel",
        label: "תווית \"למי זה מתאים\"",
        kind: "text",
        required: true,
        max: 20,
        hint: "תווית משותפת לשלושת הכרטיסים; הנקודתיים הן חלק מהטקסט" },
      { key: "includedLabel",
        label: "תווית \"מה כלול\"",
        kind: "text",
        required: true,
        max: 20,
        hint: "תווית משותפת לשלושת הכרטיסים" },
      { key: "cardCta",
        label: "כפתור בכרטיס",
        kind: "text",
        required: true,
        max: 24,
        hint: "שורה אחת, זהה בשלושת הכרטיסים" },
      { key: "sharedLine",
        label: "שורת הסיום מתחת לרשת",
        kind: "text",
        max: 120 },
      { key: "packages",
        label: "החבילות",
        kind: "repeater",
        required: true,
        itemLabel: "חבילה",
        min: 1,
        fields: [
          { key: "slug",
            label: "מזהה החבילה",
            kind: "text",
            required: true,
            max: 24,
            locked: true,
            hint: "נעול. אם המזהה לא קיים ברשימת השירותים בהגדרות, הכרטיס פשוט לא יופיע" },
          { key: "name",
            label: "שם החבילה",
            kind: "text",
            required: true,
            max: 32,
            hint: "שורה אחת. שם שנשבר לשתי שורות מזיז את כל השורות בכרטיס הזה ומוציא אותו מיישור מול שכניו" },
          { key: "chip",
            label: "צ'יפ קצר מתחת לשם",
            kind: "text",
            max: 24,
            hint: "לא חובה. המקום שמור בשלושת הכרטיסים גם כשהוא ריק, כדי שהשורות יישארו מיושרות" },
          { key: "fit",
            label: "למי זה מתאים",
            kind: "textarea",
            required: true,
            max: 120 },
          { key: "included",
            label: "מה כלול",
            kind: "repeater",
            required: true,
            itemLabel: "פריט",
            min: 1,
            fields: [
              { key: "text",
                label: "פריט ברשימה",
                kind: "text",
                max: 60 }
            ] },
          { key: "highlight",
            label: "זו החבילה המומלצת",
            kind: "boolean",
            hint: "רק חבילה אחת. היא מקבלת מסגרת זהב, רקע חם והרמה קלה — שתי חבילות מודגשות מבטלות את ההדגשה" }
        ],
        hint: "סדר הפריטים הוא סדר התצוגה: קל → עמוק" }
  ],
};

export const COACHING_PROCESS: SectionType = {
  type: "coaching-process",
  label: "מה קורה בכל שלב",
  purpose: "הסרת אי-ודאות: שלוש התחנות של התהליך, לפני הסגירה.",
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 50 },
      { key: "lead",
        label: "פסקת ההסבר",
        kind: "textarea",
        max: 180 },
      { key: "steps",
        label: "תחנות התהליך",
        kind: "repeater",
        required: true,
        itemLabel: "תחנה",
        min: 3,
        fields: [
          { key: "t",
            label: "שם התחנה",
            kind: "text",
            required: true,
            max: 34,
            hint: "שורה אחת" },
          { key: "d",
            label: "מה קורה בתחנה",
            kind: "textarea",
            max: 260 }
        ],
        hint: "שלוש תחנות הן המבנה המעוצב; רביעית עוד מחזיקה, חמישית כבר צרה מדי" },
      { key: "cta",
        label: "קישור לטופס",
        kind: "text",
        max: 60,
        hint: "החץ ← הוא חלק מהטקסט" }
  ],
};

export const COACHING_PROOF: SectionType = {
  type: "coaching-proof",
  label: "הוכחה — מהמטבח",
  purpose: "אוכל אמיתי מהמטבח שלה, וסלוט המלצות שנשאר כן עד שתגיע עדות אמיתית.",
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 23,
        hint: "התקרה הנמוכה בעמוד — הכותרת יושבת בכרטיס צר לצד התמונה" },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 14,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך הכותרת בדיוק" },
      { key: "lead",
        label: "שורת ההסבר",
        kind: "textarea",
        max: 120 },
      { key: "photo",
        label: "התמונה הגדולה",
        kind: "image",
        ratio: "3:2",
        hint: "מדממת לחצי המסך בדסקטופ ופותחת את הסקשן במובייל" },
      { key: "photoAlt",
        label: "טקסט חלופי לתמונה הגדולה",
        kind: "text",
        required: true,
        max: 100,
        hint: "שם המנה כפי שהוא בעמוד המתכון. לא לכתוב \"תמונה של\"" },
      { key: "tiles",
        label: "ריבועי המנות",
        kind: "repeater",
        itemLabel: "מנה",
        min: 2,
        fields: [
          { key: "src",
            label: "תמונת המנה",
            kind: "image",
            ratio: "1:1",
            hint: "נחתכת לריבוע (object-cover)" },
          { key: "alt",
            label: "טקסט חלופי",
            kind: "text",
            required: true,
            max: 100,
            hint: "שם המנה כפי שהוא בעמוד המתכון" }
        ],
        hint: "מספר זוגי (2 או 4)" },
      { key: "testimonialEmpty",
        label: "שורת סלוט ההמלצות",
        kind: "textarea",
        required: true,
        max: 120,
        hint: "זו ההצהרה הכנה שאין עדיין המלצות. לא לכתוב כאן המלצה שלא נאמרה באמת" },
      { key: "cta",
        label: "קישור למתכונים",
        kind: "text",
        max: 60,
        hint: "החץ ← הוא חלק מהטקסט" }
  ],
};

export const COACHING_FAQ: SectionType = {
  type: "coaching-faq",
  label: "שאלות ותשובות",
  purpose: "אחת-עשרה ההתנגדויות שחוזרות, בקולה, ומהן נבנה גם ה-FAQPage לגוגל.",
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 30,
        hint: "הכותרת הנוכחית ממלאת כמעט את כל השורה — כל תו נוסף ישבור אותה לשתי שורות" },
      { key: "lead",
        label: "פסקת ההסבר",
        kind: "textarea",
        max: 180 },
      { key: "items",
        label: "השאלות",
        kind: "repeater",
        required: true,
        itemLabel: "שאלה",
        min: 3,
        fields: [
          { key: "q",
            label: "השאלה",
            kind: "text",
            required: true,
            max: 80,
            hint: "בקולה של הגולשת, בגוף ראשון" },
          { key: "a",
            label: "התשובה",
            kind: "textarea",
            required: true,
            max: 400,
            hint: "התשובה נשלחת גם לגוגל כמות שהיא — עד 300 תווים היא מוצגת במלואה" }
        ],
        hint: "אלה גם השאלות שגוגל ומנועי-AI מציגים; סדר הפריטים הוא סדר התצוגה" },
      { key: "closeLine",
        label: "שורת הסיום",
        kind: "textarea",
        max: 140,
        hint: "הקישור \"בואי נדבר\" ממשיך את המשפט הזה באותה שורה" },
      { key: "closeCta",
        label: "הקישור בסוף השורה",
        kind: "text",
        max: 30,
        hint: "החץ ← הוא חלק מהטקסט" },
      { key: "magnet",
        label: "קישור רך למתכונים",
        kind: "text",
        max: 60 }
  ],
};

export const COACHING_CTA: SectionType = {
  type: "coaching-cta",
  label: "סגירה — בואי נדבר",
  purpose: "הדלת: הפאנל הכהה עם הטופס, ההבטחה לחזרה, ותג האמון.",
  required: true,
  pin: "end",
  fields: [
      { key: "title",
        label: "כותרת הסגירה",
        kind: "textarea",
        required: true,
        max: 54,
        lines: 2,
        maxPerLine: 26,
        hint: "שתי שורות, מופרדות ב-Enter. עד 26 תווים לשורה" },
      { key: "body",
        label: "פסקת הסגירה",
        kind: "textarea",
        required: true,
        max: 180 },
      { key: "packagesLine",
        label: "שורת החבילות",
        kind: "textarea",
        max: 160 },
      { key: "promise",
        label: "הבטחת החזרה",
        kind: "text",
        required: true,
        max: 60,
        hint: "אותה הבטחה מופיעה גם בהגדרות המערכת; שינוי כאן לא משנה אותה שם" },
      { key: "trustToken",
        label: "תג האמון",
        kind: "text",
        required: true,
        max: 76,
        hint: "בניגוד לעמוד הבית, כאן זו מחרוזת אחת ולא שתיים — הגלולה נשברת לשתי שורות בטלפון ואז מתעגלת פחות" },
      { key: "aboutPointer",
        label: "קישור לעמוד עליי",
        kind: "text",
        max: 60,
        hint: "החץ ← הוא חלק מהטקסט" },
      { key: "formHeading",
        label: "כותרת מעל הטופס",
        kind: "text",
        required: true,
        max: 40,
        hint: "בקוד המפתח נקרא button אבל זו כותרת מעל הטופס, לא תווית של כפתור" }
  ],
};

// CHANGED — replaces the existing HOME_GUIDE (the 2026-08-12 first-person
// re-set): −mechanism (the four index tabs became her hello), +introHello and
// +intro (the ruled first-person band — the labels live on inside the
// sentences), +empathyAccent (empathy now sits under the title as the
// section's centred standfirst, and the rose rule draws itself under it).
export const HOME_GUIDE: SectionType = {
  type: "home-guide",
  label: "המדריכה — «הדוסייה על השולחן»",
  purpose: "מי עומדת מאחורי האתר: הקול שלה בגוף ראשון, השם, ההסמכות, ותחומי הליווי.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה",
      kind: "text",
      required: true,
      max: 40 },
    { key: "title",
      label: "כותרת הסקשן",
      kind: "textarea",
      required: true,
      max: 42,
      hint: "clamp(1.7rem,4.4vw,3.25rem) בכותרת ממורכזת — שורה אחת" },
    { key: "titleAccent",
      label: "המילה עם הקו הוורוד",
      kind: "mark",
      of: "title",
      max: 18 },
    { key: "empathy",
      label: "פסקת האמפתיה",
      kind: "textarea",
      required: true,
      max: 180,
      // the standfirst under the centred masthead: mx-auto max-w-[60ch]
      // text-center text-[1.08rem] leading-relaxed → 60 chars a line, three
      // centred lines before it stops reading as a subtitle.
      hint: "יושבת מתחת לכותרת כתת-כותרת ממורכזת — הקול שלה, נשימה אחת" },
    { key: "empathyAccent",
      label: "המילים עם הקו הוורוד באמפתיה",
      kind: "mark",
      of: "empathy",
      max: 30,
      hint: "חייב להיות רצף מילים מתוך פסקת האמפתיה. אין התאמה — הקו פשוט לא יצויר" },
    { key: "name",
      label: "שם",
      kind: "text",
      required: true,
      max: 24 },
    { key: "role",
      label: "תפקיד",
      kind: "text",
      required: true,
      max: 46 },
    { key: "portraitAlt",
      label: "תיאור הפורטרט (alt)",
      kind: "text",
      required: true,
      max: 110,
      // the REAL portrait (cl-101) stands straight in the hairline frame
      // (aspect-[4/5]), its figcaption BELOW the pixels; the photo path is art
      // direction and stays a constant in page.tsx — only its description is
      // hers. 110 = the house alt ceiling (same as about-story imageAlt).
      hint: "פורטרט אמיתי בלבד, לעולם לא תמונה מיוצרת. לתאר מה רואים, בלי \"תמונה של\"" },
    { key: "credentials",
      label: "תגי ההסמכה",
      kind: "repeater",
      required: true,
      itemLabel: "תג",
      max: 7,
      fields: [
        { key: "",
          label: "טקסט התג",
          kind: "text",
          required: true,
          max: 40 }
      ],
      // a hairline ledger now (border-b rows at text-[13px] tracking-eyebrow),
      // not RecognitionBadges — nothing slices; the ledger simply grows a row
      // per item.
      hint: "עד שבעה — כל תג הוא שורה בפנקס, ומעבר לזה הוא מפסיק להיקרא כעובדות שקטות" },
    { key: "introHello",
      label: "פתיחת ההיכרות",
      kind: "text",
      required: true,
      max: 20,
      // the serif opening breath (font-serif text-xl font-bold) — an inline
      // span that opens the band's paragraph; the intro continues it in-line.
      hint: "משפט קצר אחד — «היי, אני אלונה.»; ההמשך נכתב בשדה הבא באותה שורה" },
    { key: "intro",
      label: "ההיכרות בגוף ראשון",
      kind: "textarea",
      required: true,
      max: 240,
      // max-w-[58ch] text-lg leading-[1.75] inside the border-y band → 58
      // chars a line, four lines before the breath stops being one.
      hint: "נשימה אחת בקולה — ארבע תוויות המנגנון חיות בתוך המשפטים, לא כרשימה" },
    { key: "areasLabel",
      label: "כותרת תחומי הליווי",
      kind: "text",
      required: true,
      max: 24,
      // text-xs font-bold tracking-eyebrow beside the ◆ — the kicker
      // treatment over the two-column list; one line.
      hint: "היהלום מצויר בקוד" },
    { key: "areas",
      label: "תחומי הליווי",
      kind: "repeater",
      required: true,
      itemLabel: "תחום",
      min: 1,
      fields: [
        { key: "",
          label: "שם התחום",
          kind: "text",
          required: true,
          max: 34,
          // text-sm font-semibold rows in the sm:grid-cols-2 list (the pills
          // retired with the paper slip) — each item one line in its column
          // (the longest today is 25 chars).
          hint: "פריט בשורה אחת" }
      ],
      hint: "רשימה בשתי עמודות ממסך 640 ומעלה; הסדר הוא סדר התצוגה" },
    { key: "areasNote",
      label: "שורת הגבול הרפואי",
      kind: "textarea",
      required: true,
      max: 120,
      // text-sm leading-relaxed at max-w-[58ch] under the list — two lines.
      hint: "מעקה ה-YMYL: לצד הרופא או הרופאה, לא במקומם — לעולם לא הבטחה למדד" },
    { key: "cta",
      label: "קישור לעמוד הליווי",
      kind: "text",
      max: 45,
      hint: "החץ ← חלק מהטקסט. היעד קבוע בקוד" }
  ],
};

export const HOME_RIBBON: SectionType = {
  type: "home-ribbon",
  label: "רצועת המנות — הערוץ באינסטגרם",
  purpose: "הוכחת-המלאכה של הדוסייה: קיר המנות האמיתיות שלה, שהוא גם ההזמנה לעקוב.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה קטנה",
      kind: "text",
      required: true,
      max: 40,
      // text-xs font-bold tracking-eyebrow, centred over the band — the same
      // eyebrow treatment as every kicker on the page.
      hint: "היהלום מצויר בקוד" },
    { key: "note",
      label: "שורת המקור",
      kind: "text",
      required: true,
      max: 90,
      // text-center text-sm text-muted directly under the band — one sentence;
      // at 390px it folds to two centred lines around 45 chars and stays calm.
      hint: "משפט אחד: מאיפה המנות באמת" },
    { key: "follow",
      label: "שורת הערוץ",
      kind: "textarea",
      max: 170,
      // mx-auto max-w-[56ch] text-sm leading-relaxed — 56 chars a line;
      // 170 keeps the follow ask to three centred lines.
      hint: "ההזמנה לעקוב — צ'יפי הרשתות עצמם מגיעים מההגדרות (SocialLinks)" },
    { key: "linkHint",
      label: "רמז הקישור לקורא-מסך",
      kind: "text",
      required: true,
      max: 60,
      hint: "לא מוצג על המסך — מוקרא אחרי שם המנה בכל אריח מקושר, כדי שלקישור תהיה מטרה בשמו" },
    { key: "tiles",
      label: "אריחי המנות",
      kind: "repeater",
      required: true,
      itemLabel: "מנה",
      min: 6,
      // the CSS loop (.dish-ribbon-track, translateX(-50%)) doubles the tiles
      // and needs ONE repeat wider than the viewport: at the md tile width
      // (212px + 18px margin) a 1280px+ screen needs at least 6 tiles or the
      // seam shows through. 13 today.
      fields: [
        { key: "src",
          label: "תמונת המנה",
          kind: "image",
          ratio: "4:5",
          minWidth: 424,
          hint: "מנה אמיתית מהמטבח שלה בלבד, חתוכה מראש ל-424×530 — האריחים עוקפים את האופטימייזר בכוונה" },
        { key: "alt",
          label: "טקסט חלופי",
          kind: "text",
          required: true,
          max: 100,
          hint: "לתאר את המנה עצמה, בלי \"תמונה של\"" }
      ],
      hint: "אלה אריחי ברירת-המחדל: ברגע שקיר-הרשתות בהגדרות מלא, הוא תופס את הרצועה (כולל קישורי פוסטים)" }
  ],
};

export const HOME_PLAN: SectionType = {
  type: "home-plan",
  label: "התוכנית — סולם שלושת השלבים",
  purpose: "שלושת השלבים של הליווי, כסולם נגלל.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה",
      kind: "text",
      required: true,
      max: 40 },
    { key: "title",
      label: "כותרת הסקשן",
      kind: "textarea",
      required: true,
      max: 42 },
    { key: "titleAccent",
      label: "המילים עם הקו הוורוד",
      kind: "mark",
      of: "title",
      max: 18 },
    { key: "lead",
      label: "משפט מקדים",
      kind: "textarea",
      max: 130,
      hint: "max-w-[60ch]" },
    { key: "steps",
      label: "שלבי הליווי",
      kind: "repeater",
      required: true,
      itemLabel: "שלב",
      max: 3,
      fields: [
        { key: "n",
          label: "מספר",
          kind: "text",
          required: true,
          max: 2 },
        { key: "t",
          label: "שם השלב",
          kind: "text",
          required: true,
          max: 42 },
        { key: "d",
          label: "תיאור השלב",
          kind: "textarea",
          required: true,
          max: 520 }
      ],
      hint: "שלושה בדיוק — הסולם מעוצב לשלוש דרגות" },
    { key: "cta",
      label: "קישור להוכחה",
      kind: "text",
      max: 60 }
  ],
};

// CHANGED — replaces the existing HOME_PROOF: the honest dark slots
// (darkTestimonial + darkLogos) came off 2026-08-12 (Rom: «במקום המקום של
// ההמלצות תעשה מקום ל-3 מאמרים») — the articles study (home-articles) took
// their place on the page. The INTEGRITY rule is untouched: no invented
// testimonials, and the consent-gated capability waits for real quotes.
export const HOME_PROOF: SectionType = {
  type: "home-proof",
  label: "הוכחה — «אני באמת מבשלת»",
  purpose: "שלושה מתכונים אמיתיים מהארכיון, נבחרים אוטומטית בכל טעינה.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה",
      kind: "text",
      required: true,
      max: 40 },
    { key: "title",
      label: "כותרת הסקשן",
      kind: "textarea",
      required: true,
      max: 42 },
    { key: "titleAccent",
      label: "המילה עם הקו הוורוד",
      kind: "mark",
      of: "title",
      max: 18 },
    { key: "body",
      label: "משפט מקדים",
      kind: "textarea",
      max: 130 },
    { key: "countChip",
      label: "צ'יפ הכמות",
      kind: "text",
      max: 42,
      hint: "חייב להתאים למספר המתכונים האמיתי בארכיון" },
    { key: "cta",
      label: "קישור לכל המתכונים",
      kind: "text",
      max: 40 }
  ],
};

export const HOME_STAKES: SectionType = {
  type: "home-stakes",
  label: "הצומת — שתי הדרכים",
  purpose: "ההשוואה בין הדרך השקטה לשנה הרועשת, ואחריה פס הפעולה.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה",
      kind: "text",
      required: true,
      max: 40 },
    { key: "title",
      label: "כותרת הסקשן",
      kind: "textarea",
      required: true,
      max: 40 },
    { key: "titleAccent",
      label: "המילה עם הקו הוורוד",
      kind: "mark",
      of: "title",
      max: 18 },
    { key: "cue",
      label: "שורת ההמלצה",
      kind: "text",
      max: 40 },
    { key: "quiet",
      label: "העמודה השקטה — הדרך המומלצת",
      kind: "group",
      fields: [
        { key: "label", label: "כותרת העמודה", kind: "text", required: true, max: 24 },
        { key: "note", label: "שורת המשנה", kind: "text", max: 60 },
        { key: "points", label: "הנקודות", kind: "repeater", itemLabel: "נקודה", min: 3, max: 5,
          fields: [{ key: "", label: "נקודה", kind: "text", max: 48 }] },
      ] },
    { key: "noisy",
      label: "העמודה הרועשת — הדרך הישנה",
      kind: "group",
      fields: [
        { key: "label", label: "כותרת העמודה", kind: "text", required: true, max: 24 },
        { key: "note", label: "שורת המשנה", kind: "text", max: 60 },
        { key: "points", label: "הנקודות", kind: "repeater", itemLabel: "נקודה", min: 3, max: 5,
          fields: [{ key: "", label: "נקודה", kind: "text", max: 48 }] },
      ] },
    { key: "band",
      label: "משפט פס הסיום",
      kind: "textarea",
      required: true,
      max: 110 },
    { key: "bandCta",
      label: "כפתור הפס",
      kind: "text",
      required: true,
      max: 18,
      hint: "שורה אחת — הפינה החתוכה נשברת אחרת" },
    { key: "bandSecondary",
      label: "קישור משני בפס",
      kind: "text",
      max: 34 }
  ],
};

// NEW type — the articles study (§06b, 2026-08-12): the quiet reading room
// after the stakes fork. The three cards themselves come LIVE from the
// articles collection (title + its own frontmatter description) and the
// section renders only when at least one article exists — the document
// carries only the strip's own words. Zero invention; the third slot fills
// itself on publish.
export const HOME_ARTICLES: SectionType = {
  type: "home-articles",
  label: "המאמרים — חדר הקריאה השקט",
  purpose: "רצועת שלושת המאמרים אחרי הצומת: הכותרת, השורה השקטה ושני הקישורים — הכרטיסים עצמם נמשכים חיים מאוסף המאמרים.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה קטנה",
      kind: "text",
      required: true,
      max: 40,
      // text-xs font-bold tracking-eyebrow, centred beside the ◆ — the same
      // eyebrow treatment as every kicker on the page.
      hint: "היהלום מצויר בקוד. משמשת גם כתג-גיבוי על כרטיס של מאמר בלי תגית משלו" },
    { key: "titleA",
      label: "הכותרת — החלק הראשון",
      kind: "text",
      required: true,
      max: 36,
      // font-serif font-black at clamp(1.5rem,2.8vw,2.2rem) → 35.2px cap,
      // centred — the full masthead line = this part + the accent after it,
      // and together they must hold one line on desktop.
      hint: "נגמרת ברווח — ההדגשה שבשדה הבא ממשיכה את המשפט באותה שורה" },
    { key: "titleAccent",
      label: "סיפא הכותרת עם הקו הוורוד",
      kind: "text",
      max: 16,
      hint: "לא רצף מתוך השדה הקודם אלא המשכו — הקו הוורוד מצייר את עצמו תחתיה (u-rose-draw)" },
    { key: "lead",
      label: "השורה השקטה מתחת לכותרת",
      kind: "textarea",
      max: 120,
      // mx-auto max-w-[60ch] text-[1.08rem] leading-relaxed → 60 chars a line,
      // two centred lines keep the standfirst quiet.
      hint: "משפט אחד, בלי הבטחות — זו תת-הכותרת של חדר הקריאה" },
    { key: "itemCta",
      label: "קישור הקריאה בכרטיס",
      kind: "text",
      required: true,
      max: 24,
      hint: "החץ ← הוא חלק מהטקסט; אותו קישור בכל שלושת הכרטיסים — היעד קבוע בקוד" },
    { key: "allCta",
      label: "קישור לכל המאמרים",
      kind: "text",
      max: 40,
      hint: "החץ ← הוא חלק מהטקסט" }
  ],
};

export const HOME_SUCCESS: SectionType = {
  type: "home-success",
  label: "השיא — «שעת הזהב»",
  purpose: "שלוש שורות של תחושה. אלה לא ציטוט ולא המלצה, ולעולם לא יסומנו ככאלה.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה",
      kind: "text",
      required: true,
      max: 40 },
    { key: "lines",
      label: "שלוש שורות ההרגשה",
      kind: "textarea",
      required: true,
      max: 92,
      lines: 3,
      maxPerLine: 45,
      hint: "שלוש שורות. כל שורה נחשפת בנפרד" },
    { key: "bridge",
      label: "כפתור המעבר לטופס",
      kind: "text",
      required: true,
      max: 32 }
  ],
};

export const HOME_CTA: SectionType = {
  type: "home-cta",
  label: "סגירה — הפאנל הנייבי",
  purpose: "הזמנה אחרונה לשיחה, מעל טופס יצירת הקשר.",
  fields: [
    { key: "title",
      label: "כותרת הסגירה",
      kind: "textarea",
      required: true,
      max: 50,
      lines: 2,
      maxPerLine: 25,
      hint: "שתי שורות" },
    { key: "body",
      label: "פסקת הסגירה",
      kind: "textarea",
      required: true,
      max: 190 },
    { key: "packages",
      label: "משפט החבילות",
      kind: "textarea",
      max: 190,
      hint: "בלי מחירים" },
    { key: "promise",
      label: "הבטחת המענה",
      kind: "text",
      required: true,
      max: 70,
      hint: "מספר ימי העסקים חייב להיות אמיתי" },
    { key: "trustToken",
      label: "תג האמון",
      kind: "text",
      required: true,
      max: 34 },
    { key: "trustTokenLicense",
      label: "סיפא הרישיון",
      kind: "text",
      max: 32,
      hint: "מוצג רק ממסך 640 ומעלה, ולכן מתחיל במפריד ‎ · ‎" }
  ],
};

export const REGISTRY: Record<string, SectionType> = Object.fromEntries(
  [
    HOME_HERO,
    HOME_GUIDE,
    HOME_RIBBON,
    HOME_PLAN,
    HOME_PROOF,
    HOME_STAKES,
    HOME_ARTICLES,
    HOME_SUCCESS,
    HOME_CTA,
    CONTACT_DOOR,
    CONTACT_LEAD,
    CONTACT_WHERE,
    ABOUT_HERO,
    ABOUT_STORY,
    ABOUT_STANDARD,
    ABOUT_ROAD,
    ABOUT_CTA,
    PAGE_META,
    COACHING_HERO,
    COACHING_PROBLEM,
    COACHING_METHOD,
    COACHING_PACKAGES,
    COACHING_PROCESS,
    COACHING_PROOF,
    COACHING_FAQ,
    COACHING_CTA
  ].map((s) => [s.type, s]),
);

export const getSectionType = (type: string): SectionType | undefined => REGISTRY[type];
