// sections/registry.ts — what the editor is allowed to change, per section type.
//
// THE REGISTRY LIVES IN CODE, NOT IN THE DATABASE. It has to version-lock with
// the components that render it: a field the desk offers but the component does
// not read is a promise the page cannot keep, and the only way to keep those in
// step is to ship them together.
//
// Every `max` is derived from the CSS of the component that renders the field —
// the clamp() font size, the container width in ch, the number of lines the
// design allows, the padding of a chamfered pill. A limit without such a
// derivation is a guess, and a guess here means either a wrapped button or a
// ceiling nobody can reach.

import type { SectionType } from "./schema";

export const HOME_HERO: SectionType = {
  type: "home-hero",
  label: "פתיח — חדר הבוקר",
  purpose: "הרגע הראשון: הסרט מלא-הרוחב, ההבטחה, והכפתור הראשי.",
  required: true,
  pin: "start",
  fields: [
    {
      key: "kicker",
      label: "שורת פתיחה קטנה",
      kind: "text",
      required: true,
      max: 48,
      // text-[13px] font-bold tracking-[0.14em] ≈ 9.5px/char in a 620px column,
      // minus the ◆ glyph and its gap. 48 keeps it to two lines at 390px.
      hint: "היהלום מצויר בקוד, אין צורך להקליד אותו",
    },
    {
      key: "title",
      label: "כותרת ראשית",
      kind: "textarea",
      required: true,
      lines: 2,
      maxPerLine: 26,
      max: 58,
      // RevealHeading splits on \n ONLY and gives each line its own mask.
      // clamp(2.1rem,5vw,3.3rem) → 52.8px cap in a 620px column ≈ 26 chars.
      // A longer line wraps INSIDE its mask and the reveal stutters.
      hint: "שתי שורות. שורה ארוכה מדי תישבר באמצע האנימציה",
    },
    {
      key: "titleAccent",
      label: "המילים עם הקו הוורוד",
      kind: "mark",
      of: "title",
      max: 20,
      hint: "חייב להיות רצף מילים מתוך שורה אחת של הכותרת",
    },
    {
      key: "lede",
      label: "פסקת הפתיחה",
      kind: "textarea",
      required: true,
      max: 160,
      // max-w-[54ch] text-lg leading-[1.7] → 54 chars a line, 3 lines before it
      // pushes the button below the fold on a phone.
    },
    {
      key: "ctaPrimary",
      label: "כפתור ראשי",
      kind: "text",
      required: true,
      max: 18,
      // btn-chamfer px-8 py-4 text-base font-bold. The clipped corner breaks if
      // the label wraps, so this one really is a single line.
      hint: "שורה אחת. טקסט ארוך ישבור את הפינה החתוכה של הכפתור",
    },
    { key: "ctaSub", label: "שורה מתחת לכפתור", kind: "text", max: 28 },
    {
      key: "trustToken",
      label: "תג האמון",
      kind: "text",
      required: true,
      max: 34,
      // rounded-full border px-4 py-2.5 text-sm ≈ 7.4px/char pill
    },
    {
      key: "trustTokenLicense",
      label: "סיפא הרישיון",
      kind: "text",
      max: 32,
      hint: "מוצג רק ממסך 640 פיקסל ומעלה, ולכן מתחיל במפריד ‎ · ‎",
    },
    { key: "ctaRecipes", label: "קישור משני למתכונים", kind: "text", max: 60 },
    {
      key: "poster",
      label: "תמונת הפתיחה של הסרט",
      kind: "image",
      ratio: "wide",
      minWidth: 1600,
      decorative: true,
      locked: true,
      hint: "הפריים האחרון של הסרט חייב להיות זהה לפריים הראשון של סקשן הגלילה",
    },
    {
      key: "filmWebm",
      label: "קובץ הסרט (webm)",
      kind: "video",
      locked: true,
      hint: "מוחלף רק יחד עם הפוסטר, דרך רום",
    },
    { key: "filmMp4", label: "קובץ הסרט (mp4)", kind: "video", locked: true },
  ],
};

export const TESTIMONIALS_HERO: SectionType = {
  type: "testimonials-hero",
  label: "פתיח — ההבטחה הכנה",
  purpose: "המסגור הכן: אין עדיין המלצות, וזו בחירה. הפסקה הראשונה היא גם תיאור העמוד בגוגל.",
  required: true,
  pin: "start",
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 32,
        hint: "היהלום ◆ מצויר בקוד, אין צורך להקליד אותו" },
      { key: "title",
        label: "כותרת ראשית",
        kind: "text",
        required: true,
        max: 24,
        hint: "שורה אחת בלבד, בלי ירידת שורה. שורה ארוכה יותר תישבר בתוך אותה מסכה והעלייה תיראה כפולה" },
      { key: "body",
        label: "פסקת הפתיחה",
        kind: "textarea",
        required: true,
        max: 160,
        hint: "זו גם השורה שגוגל מציג מתחת לכותרת — לכן התקרה קשיחה" },
      { key: "bridge",
        label: "פסקת הגשר",
        kind: "textarea",
        max: 150,
        hint: "מזכירה במילים את המתכונים והרישיון — בלי קישורים, הקישורים בבעלות הסקשן הבא" },
      { key: "invite",
        label: "שורת ההזמנה",
        kind: "text",
        max: 75 },
      { key: "cta",
        label: "קישור הפעולה",
        kind: "text",
        required: true,
        max: 28,
        hint: "החץ ← הוא חלק מהטקסט. היעד (/contact) קבוע בקוד" }
  ],
};

export const TESTIMONIALS_GRID: SectionType = {
  type: "testimonials-grid",
  label: "רשת ההמלצות — מצב ריק כן",
  purpose: "הריק המכובד: הודעה כנה במקום כרטיסי רפאים, ושתי דלתות למה שכן אמיתי היום.",
  required: true,
  fields: [
      { key: "title",
        label: "כותרת כרטיס הריק",
        kind: "text",
        required: true,
        max: 25,
        hint: "מוצג רק כשאין המלצות. ברגע שתיכנס המלצה מאושרת הכרטיס הזה נעלם לגמרי" },
      { key: "emptyLead",
        label: "שורת המצב",
        kind: "text",
        required: true,
        max: 70,
        hint: "מוצג רק במצב הריק" },
      { key: "emptyBody",
        label: "ההסבר הכן",
        kind: "textarea",
        required: true,
        max: 190,
        hint: "מוצג רק במצב הריק. זו ההבטחה של הסקשן — אל תרככי אותה לניסוח שיווקי" },
      { key: "redirectIntro",
        label: "שורת ההפניה",
        kind: "text",
        required: true,
        max: 50,
        hint: "מוצג תמיד — גם אחרי שייכנסו המלצות אמיתיות" },
      { key: "redirects",
        label: "כפתורי ההפניה",
        kind: "repeater",
        required: true,
        itemLabel: "כפתור",
        min: 2,
        fields: [
          { key: "",
            label: "טקסט הכפתור",
            kind: "text",
            max: 32 }
        ],
        hint: "היעד קבוע בקוד לפי הסדר: הראשון למתכונים, השני לעליי. שני פריטים בדיוק" },
      { key: "reciprocity",
        label: "שורת ההדדיות",
        kind: "text",
        max: 50,
        hint: "כל השורה היא קישור לטופס ההיכרות. החץ ← חלק מהטקסט" }
  ],
};

export const TESTIMONIALS_CTA: SectionType = {
  type: "testimonials-cta",
  label: "סיום — הזמנה לשיחה",
  purpose: "הסגירה: הכנות שאין בה עדויות היא עצמה ההבטחה, ומכאן לשיחת ההיכרות.",
  required: true,
  pin: "end",
  fields: [
      { key: "title",
        label: "כותרת הסיום",
        kind: "textarea",
        required: true,
        max: 60,
        lines: 2,
        maxPerLine: 28,
        hint: "שתי שורות. השורה השנייה נצבעת בזהב-רך בקוד — אל תוסיפי שורה שלישית" },
      { key: "body",
        label: "פסקת הסיום",
        kind: "textarea",
        required: true,
        max: 240 },
      { key: "packages",
        label: "שורת החבילות",
        kind: "textarea",
        max: 130,
        hint: "בלי מחירים — הכרעת השאלון Q19" },
      { key: "promise",
        label: "הבטחת המענה",
        kind: "text",
        required: true,
        max: 60,
        hint: "מספר ימי העסקים חייב להיות אמיתי — זו הבטחה, לא סלוגן" },
      { key: "trustToken",
        label: "תג האמון",
        kind: "text",
        required: true,
        max: 68,
        hint: "מספר הרישיון חייב להתאים לתעודה. שדה YMYL" },
      { key: "ctaPrimary",
        label: "כפתור ראשי",
        kind: "text",
        required: true,
        max: 30,
        hint: "שורה אחת. היעד /contact#lead קבוע בקוד" },
      { key: "ctaRecipes",
        label: "קישור רך למתכונים",
        kind: "text",
        max: 46,
        hint: "החץ ← חלק מהטקסט" }
  ],
};

export const CONTACT_DOOR: SectionType = {
  type: "contact-door",
  label: "הדלת השקטה — פתיח",
  purpose: "הרגע הראשון בעמוד: ההזמנה לשיחה, ההבטחה, והכפתור הראשי.",
  required: true,
  pin: "start",
  fields: [
      { key: "crumb",
        label: "שם העמוד בשביל הפירורים",
        kind: "text",
        required: true,
        max: 20,
        hint: "זהה לתווית בתפריט העליון (nav ב-site.ts) — שינוי כאן לא משנה את התפריט" },
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 38,
        hint: "היהלום מצויר בקוד, אין צורך להקליד אותו" },
      { key: "title",
        label: "כותרת ראשית",
        kind: "text",
        required: true,
        max: 26,
        hint: "שורה אחת. RevealHeading חותך על \\n — שורה שנשברת בתוך המסכה מגמגמת באנימציה" },
      { key: "body",
        label: "פסקת ההזמנה",
        kind: "textarea",
        required: true,
        max: 200 },
      { key: "bodyAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "body",
        hint: "חייב להיות רצף מילים מתוך פסקת ההזמנה" },
      { key: "cta",
        label: "כפתור ראשי",
        kind: "text",
        required: true,
        max: 22,
        hint: "שורה אחת. טקסט ארוך ישבור את הפינה החתוכה של הכפתור" },
      { key: "ctaSub",
        label: "שורה מתחת לכפתור",
        kind: "text",
        max: 28 },
      { key: "promise",
        label: "הבטחת הזמן",
        kind: "text",
        required: true,
        max: 44,
        hint: "אותה הבטחה חוזרת גם בסקשן הטופס וגם בסקשן «איפה נפגשות» — שינוי כאן לא מחיל את עצמו עליהן" },
      { key: "place",
        label: "שורת המקום",
        kind: "text",
        required: true,
        max: 40 },
      { key: "trustToken",
        label: "שורת הרישיון",
        kind: "text",
        required: true,
        max: 52,
        hint: "שורה שקטה מתחת לגלולה — לא גלולה מתחרה" }
  ],
};

export const CONTACT_LEAD: SectionType = {
  type: "contact-lead",
  label: "רצפת-החיכוך — כרטיס הטופס",
  purpose: "הדבר החשוב בעמוד: הכותרת, ההסבר על החבילות, טופס ≤5 שדות, וואטסאפ ומסך-תודה.",
  required: true,
  fields: [
      { key: "title",
        label: "כותרת הכרטיס",
        kind: "textarea",
        required: true,
        max: 48,
        hint: "שתי שורות לכל היותר — הכותרת יושבת בתוך מסכת-חשיפה אחת" },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 16,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך הכותרת" },
      { key: "body",
        label: "פסקת ההסבר",
        kind: "textarea",
        required: true,
        max: 140 },
      { key: "packages",
        label: "פסקת החבילות",
        kind: "textarea",
        max: 160,
        hint: "בלי מחירים — ההכרעה היא שהמחיר נאמר בשיחה" },
      { key: "nameLabel",
        label: "תווית: שם",
        kind: "text",
        required: true,
        max: 24 },
      { key: "phoneLabel",
        label: "תווית: טלפון",
        kind: "text",
        required: true,
        max: 28 },
      { key: "messageLabel",
        label: "תווית: הודעה",
        kind: "text",
        max: 44,
        hint: "שדה לא חובה — «(לא חובה)» הוא חלק מהתווית, אין תג נפרד" },
      { key: "emailLabel",
        label: "תווית: אימייל",
        kind: "text",
        required: true,
        max: 20,
        hint: "משמשת גם כתווית השדה וגם ככיתוב של כפתור «+ אימייל» שפותח אותו" },
      { key: "consentLabel",
        label: "שורת ההסכמה",
        kind: "textarea",
        required: true,
        max: 70,
        hint: "חובה משפטית — חייבת לתאר את הערוצים שבהם יוצרים קשר" },
      { key: "submitLabel",
        label: "כפתור שליחה",
        kind: "text",
        required: true,
        max: 28,
        hint: "שורה אחת. זה הכפתור הכי חשוב באתר" },
      { key: "submittingLabel",
        label: "תווית בזמן שליחה",
        kind: "text",
        max: 16,
        locked: true,
        hint: "מחרוזת-מערכת, זהה לטופס הכללי (ContactLeadForm) — נעולה כדי ששני הטפסים לא ייפרדו" },
      { key: "whatsappLabel",
        label: "שורת הוואטסאפ",
        kind: "text",
        required: true,
        max: 44,
        hint: "מספר הטלפון לעולם לא מודפס — רק הקישור לוואטסאפ" },
      { key: "thanks",
        label: "מסך-תודה: המשפט",
        kind: "textarea",
        required: true,
        max: 140,
        hint: "משחזר את ההבטחה — הלקוחה קוראת אותו מיד אחרי השליחה" },
      { key: "thanksLink",
        label: "המילים שהופכות לקישור",
        kind: "mark",
        max: 24,
        of: "thanks",
        hint: "רצף מילים מתוך משפט התודה — היעד (/מתכונים) קבוע בקוד" },
      { key: "promise",
        label: "הבטחת הזמן",
        kind: "text",
        required: true,
        max: 44,
        hint: "אותה הבטחה מופיעה גם בפתיח וגם בסקשן «איפה נפגשות»" },
      { key: "place",
        label: "שורת המקום",
        kind: "text",
        required: true,
        max: 48 },
      { key: "trustToken",
        label: "שורת הרישיון",
        kind: "text",
        required: true,
        max: 56 }
  ],
};

export const CONTACT_WHERE: SectionType = {
  type: "contact-where",
  label: "איפה נפגשות",
  purpose: "שלוש הדרכים האמיתיות להיפגש: אונליין, קליניקה ברעננה, וואטסאפ בין הפגישות.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 38 },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "textarea",
        required: true,
        max: 74,
        lines: 2,
        maxPerLine: 36,
        hint: "שתי שורות, מופרדות ב-Enter. כל שורה מקבלת מסכת-חשיפה משלה" },
      { key: "body",
        label: "פסקת ההסבר",
        kind: "textarea",
        required: true,
        max: 190 },
      { key: "items",
        label: "הדרכים להיפגש",
        kind: "repeater",
        required: true,
        itemLabel: "דרך",
        min: 1,
        fields: [
          { key: "title",
            label: "כותרת הדרך",
            kind: "text",
            required: true,
            max: 34,
            hint: "הקו הוורוד נמשך על כל הכותרת, ולכן אין כאן שדה-סימון נפרד" },
          { key: "body",
            label: "תיאור הדרך",
            kind: "text",
            required: true,
            max: 90 }
        ] },
      { key: "chip",
        label: "גלולת ההבטחה",
        kind: "text",
        required: true,
        max: 44,
        hint: "אותה הבטחה שמופיעה בפתיח ובכרטיס הטופס" }
  ],
};

export const ABOUT_HERO: SectionType = {
  type: "about-hero",
  label: "פתיח — נעים להכיר",
  purpose: "הרגע הראשון של העמוד: השם, הרישיון, משבצת הפורטרט והכפתור לשיחה.",
  required: true,
  pin: "start",
  fields: [
      { key: "crumbLabel",
        label: "שם העמוד בשביל הניווט",
        kind: "text",
        required: true,
        max: 18,
        hint: "הפירור «בית» נוסף אוטומטית בקוד" },
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 48,
        hint: "היהלום מצויר בקוד, אין צורך להקליד אותו" },
      { key: "title",
        label: "השם (הכותרת הראשית)",
        kind: "text",
        required: true,
        max: 20,
        hint: "שורה אחת. איות מחייב: אקרלינג, לא אקרלינק" },
      { key: "lede",
        label: "פסקת הפתיחה",
        kind: "textarea",
        required: true,
        max: 156,
        hint: "זו גם תיאור העמוד למנועי חיפוש (meta description)" },
      { key: "licenseChip",
        label: "תג הרישיון",
        kind: "text",
        required: true,
        max: 64,
        hint: "שורה אחת. זו הצהרה רגולטורית, לשנות רק מול התעודה" },
      { key: "ctaPrimary",
        label: "כפתור ראשי",
        kind: "text",
        required: true,
        max: 18,
        hint: "שורה אחת. טקסט ארוך ישבור את הפינה החתוכה של הכפתור" },
      { key: "ctaPrimarySub",
        label: "שורה מתחת לכפתור",
        kind: "text",
        max: 28,
        hint: "מתחברת בקוד לשורה אחת עם השורה הקטנה, עם ‎ · ‎ באמצע" },
      { key: "ctaMicro",
        label: "השורה הקטנה שאחריה",
        kind: "text",
        max: 38,
        hint: "מתחברת בקוד לשורה אחת עם השורה שמתחת לכפתור" },
      { key: "ctaSecondary",
        label: "קישור משני אל הסיפור",
        kind: "text",
        max: 30,
        hint: "החץ ↓ הוא חלק מהטקסט" },
      { key: "portraitLabel",
        label: "תיאור הפורטרט (alt)",
        kind: "text",
        max: 110,
        hint: "לא מוצג היום. שמור לרגע שבו יגיע פורטרט אמיתי 4:5. פורטרט אמיתי בלבד, לעולם לא תמונה מיוצרת" },
      { key: "portraitSignature",
        label: "החתימה בכרטיס-הביקור",
        kind: "text",
        max: 10,
        hint: "השם הפרטי בכתב-יד. אותו ערך שמופיע גם בסוף המכתב" },
      { key: "portraitRole",
        label: "התפקיד בכרטיס-הביקור",
        kind: "text",
        max: 40,
        hint: "אותו נוסח כמו כותרת התעודה בסקשן ההסמכות" }
  ],
};

export const ABOUT_STORY: SectionType = {
  type: "about-story",
  label: "הסיפור שלי — המכתב החתום",
  purpose: "סיפור-המקור כמכתב אישי חתום, על רקע מנה אמיתית מהמטבח.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסיפור",
        kind: "textarea",
        required: true,
        max: 48,
        lines: 2,
        maxPerLine: 23,
        hint: "שתי שורות. שורה ארוכה מדי תישבר באמצע האנימציה" },
      { key: "p1",
        label: "פסקה ראשונה",
        kind: "textarea",
        required: true,
        max: 200 },
      { key: "p2",
        label: "פסקה שנייה",
        kind: "textarea",
        required: true,
        max: 200 },
      { key: "credo1",
        label: "האני-מאמין, משפט ראשון",
        kind: "textarea",
        required: true,
        max: 120 },
      { key: "credo2",
        label: "האני-מאמין, משפט שני",
        kind: "textarea",
        required: true,
        max: 120,
        hint: "המילה עם הקו הוורוד חייבת להופיע כאן ככתבה" },
      { key: "credo2Accent",
        label: "המילה עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "credo2",
        hint: "חייב להיות רצף מילים מתוך המשפט השני, בשורה אחת. אין התאמה — הקו פשוט לא יצויר" },
      { key: "signOff",
        label: "שורת הסיום",
        kind: "text",
        max: 60 },
      { key: "signature",
        label: "החתימה",
        kind: "text",
        max: 12 },
      { key: "image",
        label: "תמונת המנה שברקע",
        kind: "image",
        ratio: "3:4",
        hint: "מוצגת פעמיים: כעמודה גבוהה בצד במסך רחב, וכרצועה 3:2 בראש העמוד בנייד. תמונה לאורך תעבוד בשתיהן. מנה אמיתית מהמטבח שלה בלבד" },
      { key: "imageAlt",
        label: "תיאור התמונה (alt)",
        kind: "text",
        required: true,
        max: 110,
        hint: "מתאר את הרצועה בנייד. העותק במסך רחב הוא דקורטיבי ומקבל alt ריק" }
  ],
};

export const ABOUT_AGE: SectionType = {
  type: "about-age",
  label: "על הגיל — הציטוט הגדול",
  purpose: "התשובה לשאלת הגיל, כטיפוגרפיה מדורגת עם חותם בכתב-יד.",
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "quote",
        label: "הציטוט",
        kind: "textarea",
        required: true,
        max: 130,
        lines: 4,
        maxPerLine: 38,
        hint: "ארבע שורות שיורדות במדרגות. כל שורה נחשפת בנפרד" },
      { key: "quoteAccent",
        label: "המילה עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "quote",
        hint: "שימי לב: הקוד מסמן את המילה בכל שורה שהיא מופיעה בה (ורק את המופע הראשון בכל שורה). מילה נפוצה תקבל כמה קווים" },
      { key: "support",
        label: "שורת התמיכה",
        kind: "textarea",
        max: 76 },
      { key: "signature",
        label: "החתימה",
        kind: "text",
        max: 12 }
  ],
};

export const ABOUT_CREDENTIALS: SectionType = {
  type: "about-credentials",
  label: "הרקע — קיר ההסמכות",
  purpose: "פנקס האימות: תעודת הרישיון עם כפתור בדיקה, שתי שורות רשומה, והצד האנושי — דיאטנית שמבשלת.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 45 },
      { key: "titleAccent",
        label: "המילה עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך הכותרת. אין התאמה — הקו פשוט לא יצויר" },
      { key: "anchorTitle",
        label: "תעודה — כותרת",
        kind: "text",
        required: true,
        max: 38 },
      { key: "anchorLine",
        label: "תעודה — מספר הרישיון",
        kind: "text",
        required: true,
        max: 44,
        hint: "נתון רגולטורי. לשנות רק מול התעודה" },
      { key: "anchorVerify",
        label: "תעודה — כפתור הבדיקה",
        kind: "text",
        required: true,
        max: 40,
        hint: "שורה אחת. זו הבטחת הבדיקוּת של העמוד" },
      { key: "anchorVerifyHref",
        label: "תעודה — קישור למאגר",
        kind: "link",
        locked: true,
        hint: "מאגר מורשי משרד הבריאות. נעול: קישור שגוי הופך הבטחת אימות למבוי סתום. נפתח בלשונית חדשה" },
      { key: "bscTitle",
        label: "רשומה 1 — כותרת",
        kind: "text",
        required: true,
        max: 44 },
      { key: "bscLine",
        label: "רשומה 1 — פירוט",
        kind: "text",
        max: 60 },
      { key: "internTitle",
        label: "רשומה 2 — כותרת",
        kind: "text",
        required: true,
        max: 44 },
      { key: "internLine",
        label: "רשומה 2 — פירוט",
        kind: "text",
        max: 60 },
      { key: "craftTitle",
        label: "דיאטנית שמבשלת — כותרת",
        kind: "text",
        required: true,
        max: 36 },
      { key: "craftLine",
        label: "דיאטנית שמבשלת — טקסט",
        kind: "textarea",
        required: true,
        max: 165 },
      { key: "craftLink",
        label: "קישור למתכונים",
        kind: "text",
        max: 24,
        hint: "החץ ← הוא חלק מהטקסט" },
      { key: "craftMicro",
        label: "השורה הקטנה ליד הקישור",
        kind: "text",
        max: 40,
        hint: "מספר המתכונים. לעדכן כשהארכיון גדל" },
      { key: "craftImage",
        label: "תמונת המנה",
        kind: "image",
        ratio: "3:2",
        hint: "מנה אמיתית מהמטבח שלה בלבד. לא תמונת סטוק ולא תמונה מיוצרת" },
      { key: "craftImageAlt",
        label: "תיאור התמונה (alt)",
        kind: "text",
        required: true,
        max: 110 },
      { key: "bridge",
        label: "שורת הגישור",
        kind: "textarea",
        max: 124 },
      { key: "teamLink",
        label: "קישור לעמוד ההסמכות המלא",
        kind: "text",
        max: 32,
        hint: "החץ ← הוא חלק מהטקסט" }
  ],
};

export const ABOUT_PRESS: SectionType = {
  type: "about-press",
  label: "מדיה ושיתופי פעולה",
  purpose: "המקום ששמור ללוגואים, כל עוד הוא ריק — הצהרה למה הוא ריק.",
  fields: [
      { key: "reserved",
        label: "ההודעה בזמן שהמקום שמור",
        kind: "textarea",
        required: true,
        max: 110 }
  ],
};

export const ABOUT_CTA: SectionType = {
  type: "about-cta",
  label: "סגירה — הצעד שלך",
  purpose: "ההזמנה לשיחה בלי לחץ, עם דלת צדדית למתכונים.",
  required: true,
  pin: "end",
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסגירה",
        kind: "textarea",
        required: true,
        max: 70,
        lines: 2,
        maxPerLine: 46,
        hint: "שתי שורות. השורה השנייה כבר על הגבול — כל תוספת תעטוף גם במסך רחב" },
      { key: "body",
        label: "פסקת הסגירה",
        kind: "textarea",
        required: true,
        max: 260 },
      { key: "recipes",
        label: "קישור צדדי למתכונים",
        kind: "text",
        max: 56,
        hint: "החץ ← הוא חלק מהטקסט" },
      { key: "trustToken",
        label: "תג האמון",
        kind: "text",
        required: true,
        max: 64,
        hint: "הצהרה רגולטורית. לשנות רק מול התעודה" },
      { key: "button",
        label: "כפתור ראשי",
        kind: "text",
        required: true,
        max: 30,
        hint: "שורה אחת. טקסט ארוך ישבור את הפינה החתוכה של הכפתור" },
      { key: "signature",
        label: "החתימה",
        kind: "text",
        max: 12 }
  ],
};

export const PAGE_META: SectionType = {
  type: "page-meta",
  label: "כותרת ותיאור לגוגל",
  purpose: "מה שגוגל ומנועי-התשובות רואים, ושם השירות ב-Schema.",
  required: true,
  pin: "start",
  fields: [
      { key: "title",
        label: "כותרת העמוד בגוגל",
        kind: "text",
        required: true,
        max: 42,
        hint: "מופיע גם בלשונית הדפדפן; \"| אלונה אקרלינג\" מתווסף אוטומטית" },
      { key: "serviceName",
        label: "שם השירות בנתוני-Schema",
        kind: "text",
        max: 60,
        hint: "לא נראה לגולשת — זה מה שגוגל קורא כשם השירות" },
      { key: "serviceType",
        label: "סוג השירות בנתוני-Schema",
        kind: "text",
        max: 60,
        hint: "היום זהה לשם השירות" }
  ],
};

export const COACHING_HERO: SectionType = {
  type: "coaching-hero",
  label: "פתיח — שולחן הייעוץ",
  purpose: "הרגע הראשון: ההבטחה, תג האמון, ושני הכפתורים.",
  required: true,
  pin: "start",
  fields: [
      { key: "breadcrumb",
        label: "שם העמוד בשביל-הפירורים",
        kind: "text",
        required: true,
        max: 40,
        hint: "בדרך כלל זהה לכותרת העמוד בגוגל; מוזן גם ל-BreadcrumbList" },
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40,
        hint: "היהלום מצויר בקוד, אין צורך להקליד אותו" },
      { key: "title",
        label: "כותרת ראשית",
        kind: "text",
        required: true,
        max: 24,
        hint: "שורה אחת. אפשר לשבור עם Enter, אבל כל שורה מוגבלת ל-24 — שורה ארוכה יותר נשברת בתוך מסכת האנימציה" },
      { key: "body",
        label: "פסקת הפתיחה",
        kind: "textarea",
        required: true,
        max: 160,
        hint: "זו גם הפסקה שמופיעה בגוגל מתחת לכותרת — לכן עד 160 תווים" },
      { key: "trustToken",
        label: "תג האמון",
        kind: "text",
        required: true,
        max: 76,
        hint: "מתחת ל-640px מותר לה להישבר לשתי שורות; מ-640px ומעלה חייבת שורה אחת" },
      { key: "ctaPrimary",
        label: "כפתור ראשי",
        kind: "text",
        required: true,
        max: 20,
        hint: "שורה אחת. טקסט ארוך ישבור את הפינה החתוכה" },
      { key: "ctaSub",
        label: "שורה מתחת לכפתור",
        kind: "text",
        max: 24 },
      { key: "ctaWhatsapp",
        label: "כפתור וואטסאפ",
        kind: "text",
        max: 32,
        hint: "שורה אחת. הקישור עצמו לוואטסאפ נקבע בהגדרות" },
      { key: "micro",
        label: "שורת ההרגעה מתחת לכפתורים",
        kind: "text",
        max: 90,
        hint: "הנקודות המפרידות (·) הן חלק מהטקסט ונכתבות ידנית" }
  ],
};

export const COACHING_PROBLEM: SectionType = {
  type: "coaching-problem",
  label: "למה דווקא ליווי — הפער",
  purpose: "הרגע שבו נאמר שהפער הוא ה\"לבד\", לא הידע.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40,
        hint: "היהלום מצויר בקוד" },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 30,
        hint: "שורה אחת. הסקשן צר (עמודת קריאה) ולכן התקרה נמוכה מזו של סקשן רחב" },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך הכותרת בדיוק, אחרת הקו פשוט לא יצויר" },
      { key: "lead",
        label: "שורת המשנה",
        kind: "text",
        max: 120,
        hint: "בקוד השדה נקרא subtitle אך מוזן ל-prop בשם lead" },
      { key: "body1",
        label: "פסקה ראשונה",
        kind: "textarea",
        required: true,
        max: 220 },
      { key: "quote",
        label: "הציטוט הגדול",
        kind: "text",
        required: true,
        max: 100,
        hint: "משפט אחד וחזק. הוא נקודת המנוחה של העמוד, לא עוד פסקה" },
      { key: "quoteAccent",
        label: "המילה המודגשת בציטוט",
        kind: "mark",
        max: 12,
        of: "quote",
        hint: "בדרך כלל מילה אחת. חייבת להופיע בציטוט בדיוק" },
      { key: "body2",
        label: "פסקה שנייה",
        kind: "textarea",
        required: true,
        max: 220 },
      { key: "cta",
        label: "קישור לסקשן השיטה",
        kind: "text",
        max: 60,
        hint: "החץ ← הוא חלק מהטקסט ונכתב ידנית" }
  ],
};

export const COACHING_METHOD: SectionType = {
  type: "coaching-method",
  label: "השיטה — ארבעת העמודים",
  purpose: "ארבע הטענות שהופכות ידע לתוצאה; זה הרגע הנעוץ היחיד בעמוד.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 50,
        hint: "שורה אחת" },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך הכותרת בדיוק" },
      { key: "pillars",
        label: "עמודי השיטה",
        kind: "repeater",
        required: true,
        itemLabel: "עמוד",
        min: 2,
        fields: [
          { key: "title",
            label: "כותרת העמוד",
            kind: "text",
            required: true,
            max: 38,
            hint: "שורה אחת. הספרה הרפאים עולה מאחורי הכותרת בלבד" },
          { key: "body",
            label: "גוף העמוד",
            kind: "textarea",
            required: true,
            max: 280,
            hint: "עד שבע שורות. גוף ארוך יותר יגלוש מהכרטיס בחפיסה הנעוצה" }
        ],
        hint: "סדר הכרטיסים הוא סדר החלוקה בחפיסה; המספור נוצר אוטומטית" },
      { key: "cta",
        label: "קישור לחבילות",
        kind: "text",
        max: 60,
        hint: "החץ ← הוא חלק מהטקסט" }
  ],
};

export const COACHING_PACKAGES: SectionType = {
  type: "coaching-packages",
  label: "שלוש החבילות",
  purpose: "שלוש דרכי הכניסה לליווי, בלי מחיר, זו לצד זו להשוואה.",
  required: true,
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40,
        hint: "משמש גם כשם קטלוג ההצעות בנתוני ה-Schema של העמוד" },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 50 },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 20,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך הכותרת בדיוק" },
      { key: "lead",
        label: "פסקת ההסבר",
        kind: "textarea",
        max: 180 },
      { key: "facts",
        label: "רצועת העובדות",
        kind: "repeater",
        itemLabel: "עובדה",
        min: 0,
        fields: [
          { key: "text",
            label: "טקסט העובדה",
            kind: "text",
            max: 28 }
        ],
        hint: "שים לב: הטקסטים כאן משכפלים ידנית שמות חבילות ואת שורת ההרגעה בפתיח — עדכון שם חבילה לא יעדכן אותם" },
      { key: "fitLabel",
        label: "תווית \"למי זה מתאים\"",
        kind: "text",
        required: true,
        max: 20,
        hint: "תווית משותפת לשלושת הכרטיסים; הנקודתיים הן חלק מהטקסט" },
      { key: "includedLabel",
        label: "תווית \"מה כלול\"",
        kind: "text",
        required: true,
        max: 20,
        hint: "תווית משותפת לשלושת הכרטיסים" },
      { key: "cardCta",
        label: "כפתור בכרטיס",
        kind: "text",
        required: true,
        max: 24,
        hint: "שורה אחת, זהה בשלושת הכרטיסים" },
      { key: "sharedLine",
        label: "שורת הסיום מתחת לרשת",
        kind: "text",
        max: 120 },
      { key: "packages",
        label: "החבילות",
        kind: "repeater",
        required: true,
        itemLabel: "חבילה",
        min: 1,
        fields: [
          { key: "slug",
            label: "מזהה החבילה",
            kind: "text",
            required: true,
            max: 24,
            locked: true,
            hint: "נעול. אם המזהה לא קיים ברשימת השירותים בהגדרות, הכרטיס פשוט לא יופיע" },
          { key: "name",
            label: "שם החבילה",
            kind: "text",
            required: true,
            max: 32,
            hint: "שורה אחת. שם שנשבר לשתי שורות מזיז את כל השורות בכרטיס הזה ומוציא אותו מיישור מול שכניו" },
          { key: "chip",
            label: "צ'יפ קצר מתחת לשם",
            kind: "text",
            max: 24,
            hint: "לא חובה. המקום שמור בשלושת הכרטיסים גם כשהוא ריק, כדי שהשורות יישארו מיושרות" },
          { key: "fit",
            label: "למי זה מתאים",
            kind: "textarea",
            required: true,
            max: 120 },
          { key: "included",
            label: "מה כלול",
            kind: "repeater",
            required: true,
            itemLabel: "פריט",
            min: 1,
            fields: [
              { key: "text",
                label: "פריט ברשימה",
                kind: "text",
                max: 60 }
            ] },
          { key: "highlight",
            label: "זו החבילה המומלצת",
            kind: "boolean",
            hint: "רק חבילה אחת. היא מקבלת מסגרת זהב, רקע חם והרמה קלה — שתי חבילות מודגשות מבטלות את ההדגשה" }
        ],
        hint: "סדר הפריטים הוא סדר התצוגה: קל → עמוק" }
  ],
};

export const COACHING_PROCESS: SectionType = {
  type: "coaching-process",
  label: "מה קורה בכל שלב",
  purpose: "הסרת אי-ודאות: שלוש התחנות של התהליך, לפני הסגירה.",
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 50 },
      { key: "lead",
        label: "פסקת ההסבר",
        kind: "textarea",
        max: 180 },
      { key: "steps",
        label: "תחנות התהליך",
        kind: "repeater",
        required: true,
        itemLabel: "תחנה",
        min: 3,
        fields: [
          { key: "t",
            label: "שם התחנה",
            kind: "text",
            required: true,
            max: 34,
            hint: "שורה אחת" },
          { key: "d",
            label: "מה קורה בתחנה",
            kind: "textarea",
            max: 260 }
        ],
        hint: "שלוש תחנות הן המבנה המעוצב; רביעית עוד מחזיקה, חמישית כבר צרה מדי" },
      { key: "cta",
        label: "קישור לטופס",
        kind: "text",
        max: 60,
        hint: "החץ ← הוא חלק מהטקסט" }
  ],
};

export const COACHING_PROOF: SectionType = {
  type: "coaching-proof",
  label: "הוכחה — מהמטבח",
  purpose: "אוכל אמיתי מהמטבח שלה, וסלוט המלצות שנשאר כן עד שתגיע עדות אמיתית.",
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 23,
        hint: "התקרה הנמוכה בעמוד — הכותרת יושבת בכרטיס צר לצד התמונה" },
      { key: "titleAccent",
        label: "המילים עם הקו הוורוד",
        kind: "mark",
        max: 14,
        of: "title",
        hint: "חייב להיות רצף מילים מתוך הכותרת בדיוק" },
      { key: "lead",
        label: "שורת ההסבר",
        kind: "textarea",
        max: 120 },
      { key: "photo",
        label: "התמונה הגדולה",
        kind: "image",
        ratio: "3:2",
        hint: "מדממת לחצי המסך בדסקטופ ופותחת את הסקשן במובייל" },
      { key: "photoAlt",
        label: "טקסט חלופי לתמונה הגדולה",
        kind: "text",
        required: true,
        max: 100,
        hint: "שם המנה כפי שהוא בעמוד המתכון. לא לכתוב \"תמונה של\"" },
      { key: "tiles",
        label: "ריבועי המנות",
        kind: "repeater",
        itemLabel: "מנה",
        min: 2,
        fields: [
          { key: "src",
            label: "תמונת המנה",
            kind: "image",
            ratio: "1:1",
            hint: "נחתכת לריבוע (object-cover)" },
          { key: "alt",
            label: "טקסט חלופי",
            kind: "text",
            required: true,
            max: 100,
            hint: "שם המנה כפי שהוא בעמוד המתכון" }
        ],
        hint: "מספר זוגי (2 או 4)" },
      { key: "testimonialEmpty",
        label: "שורת סלוט ההמלצות",
        kind: "textarea",
        required: true,
        max: 120,
        hint: "זו ההצהרה הכנה שאין עדיין המלצות. לא לכתוב כאן המלצה שלא נאמרה באמת" },
      { key: "cta",
        label: "קישור למתכונים",
        kind: "text",
        max: 60,
        hint: "החץ ← הוא חלק מהטקסט" }
  ],
};

export const COACHING_FAQ: SectionType = {
  type: "coaching-faq",
  label: "שאלות ותשובות",
  purpose: "אחת-עשרה ההתנגדויות שחוזרות, בקולה, ומהן נבנה גם ה-FAQPage לגוגל.",
  fields: [
      { key: "kicker",
        label: "שורת פתיחה קטנה",
        kind: "text",
        required: true,
        max: 40 },
      { key: "title",
        label: "כותרת הסקשן",
        kind: "text",
        required: true,
        max: 30,
        hint: "הכותרת הנוכחית ממלאת כמעט את כל השורה — כל תו נוסף ישבור אותה לשתי שורות" },
      { key: "lead",
        label: "פסקת ההסבר",
        kind: "textarea",
        max: 180 },
      { key: "items",
        label: "השאלות",
        kind: "repeater",
        required: true,
        itemLabel: "שאלה",
        min: 3,
        fields: [
          { key: "q",
            label: "השאלה",
            kind: "text",
            required: true,
            max: 80,
            hint: "בקולה של הגולשת, בגוף ראשון" },
          { key: "a",
            label: "התשובה",
            kind: "textarea",
            required: true,
            max: 400,
            hint: "התשובה נשלחת גם לגוגל כמות שהיא — עד 300 תווים היא מוצגת במלואה" }
        ],
        hint: "אלה גם השאלות שגוגל ומנועי-AI מציגים; סדר הפריטים הוא סדר התצוגה" },
      { key: "closeLine",
        label: "שורת הסיום",
        kind: "textarea",
        max: 140,
        hint: "הקישור \"בואי נדבר\" ממשיך את המשפט הזה באותה שורה" },
      { key: "closeCta",
        label: "הקישור בסוף השורה",
        kind: "text",
        max: 30,
        hint: "החץ ← הוא חלק מהטקסט" },
      { key: "magnet",
        label: "קישור רך למתכונים",
        kind: "text",
        max: 60 }
  ],
};

export const COACHING_CTA: SectionType = {
  type: "coaching-cta",
  label: "סגירה — בואי נדבר",
  purpose: "הדלת: הפאנל הכהה עם הטופס, ההבטחה לחזרה, ותג האמון.",
  required: true,
  pin: "end",
  fields: [
      { key: "title",
        label: "כותרת הסגירה",
        kind: "textarea",
        required: true,
        max: 54,
        lines: 2,
        maxPerLine: 26,
        hint: "שתי שורות, מופרדות ב-Enter. עד 26 תווים לשורה" },
      { key: "body",
        label: "פסקת הסגירה",
        kind: "textarea",
        required: true,
        max: 180 },
      { key: "packagesLine",
        label: "שורת החבילות",
        kind: "textarea",
        max: 160 },
      { key: "promise",
        label: "הבטחת החזרה",
        kind: "text",
        required: true,
        max: 60,
        hint: "אותה הבטחה מופיעה גם בהגדרות המערכת; שינוי כאן לא משנה אותה שם" },
      { key: "trustToken",
        label: "תג האמון",
        kind: "text",
        required: true,
        max: 76,
        hint: "בניגוד לעמוד הבית, כאן זו מחרוזת אחת ולא שתיים — הגלולה נשברת לשתי שורות בטלפון ואז מתעגלת פחות" },
      { key: "aboutPointer",
        label: "קישור לעמוד עליי",
        kind: "text",
        max: 60,
        hint: "החץ ← הוא חלק מהטקסט" },
      { key: "formHeading",
        label: "כותרת מעל הטופס",
        kind: "text",
        required: true,
        max: 40,
        hint: "בקוד המפתח נקרא button אבל זו כותרת מעל הטופס, לא תווית של כפתור" }
  ],
};

export const HOME_FILM: SectionType = {
  type: "home-film",
  label: "סרט הגלילה — «בניית המנה»",
  purpose: "הרגע החתימתי של האתר. הטקסטים כאן מופיעים לפי מיקום בגלילה, והתזמון עצמו נעול.",
  fields: [
    { key: "kicker",
      label: "צ'יפ הפתיחה על הסרט",
      kind: "text",
      required: true,
      max: 36,
      hint: "rounded-full px-4 py-1.5 text-[13px] font-semibold — גלולה בשורה אחת" },
    { key: "staticKicker",
      label: "שורת פתיחה — גרסה סטטית",
      kind: "text",
      required: true,
      max: 36 },
    { key: "staticHeading",
      label: "כותרת — גרסה סטטית",
      kind: "textarea",
      required: true,
      max: 80,
      hint: "זו הכותרת שמנועי חיפוש וקוראי-מסך מקבלים. לא טקסט גיבוי, אלא הקופי האמיתי של הסקשן" },
    { key: "staticBody",
      label: "פסקה — גרסה סטטית",
      kind: "textarea",
      required: true,
      max: 320,
      hint: "מה שרואה מי שגלילה לא עובדת אצלו, וגם גוגל" },
    { key: "finalAlt",
      label: "תיאור התמונה המסכמת",
      kind: "text",
      required: true,
      max: 125,
      hint: "נקרא בקול לקוראי-מסך" },
    { key: "chips",
      label: "צ'יפי המחשבות",
      kind: "repeater",
      itemLabel: "מחשבה",
      max: 5,
      fields: [
        { key: "",
          label: "טקסט המחשבה",
          kind: "text",
          required: true,
          max: 34 }
      ],
      hint: "חמש מחשבות שנערמות ונעלמות יחד. המיקום והתזמון על המסך נעולים" },
    { key: "captions",
      label: "כיתובי התחנות",
      kind: "repeater",
      itemLabel: "כיתוב",
      max: 4,
      fields: [
        { key: "big",
          label: "שורה גדולה",
          kind: "text",
          required: true,
          max: 48 },
        { key: "small",
          label: "שורה קטנה",
          kind: "text",
          max: 90 }
      ],
      hint: "ארבע תחנות: פתיחה, תפנית, שיא, סיום" }
  ],
};

export const HOME_GUIDE: SectionType = {
  type: "home-guide",
  label: "המדריכה — «הדוסייה על השולחן»",
  purpose: "מי עומדת מאחורי האתר: האמפתיה, השם, ההסמכות.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה",
      kind: "text",
      required: true,
      max: 40 },
    { key: "title",
      label: "כותרת הסקשן",
      kind: "textarea",
      required: true,
      max: 42,
      hint: "clamp(1.7rem,4.4vw,3.25rem) בעמודה צרה — שורה אחת" },
    { key: "titleAccent",
      label: "המילה עם הקו הוורוד",
      kind: "mark",
      of: "title",
      max: 18 },
    { key: "empathy",
      label: "פסקת האמפתיה",
      kind: "textarea",
      required: true,
      max: 260,
      hint: "max-w-[62ch] בתוך כרטיס" },
    { key: "name",
      label: "שם",
      kind: "text",
      required: true,
      max: 24 },
    { key: "role",
      label: "תפקיד",
      kind: "text",
      required: true,
      max: 46 },
    { key: "credentials",
      label: "תגי ההסמכה",
      kind: "repeater",
      required: true,
      itemLabel: "תג",
      max: 7,
      fields: [
        { key: "",
          label: "טקסט התג",
          kind: "text",
          required: true,
          max: 40 }
      ],
      hint: "עד שבעה. מעבר לזה הקומפוננטה חותכת בשקט" },
    { key: "mechanism",
      label: "לשוניות המנגנון",
      kind: "repeater",
      itemLabel: "לשונית",
      max: 4,
      fields: [
        { key: "",
          label: "טקסט הלשונית",
          kind: "text",
          required: true,
          max: 24 }
      ] },
    { key: "cta",
      label: "קישור לעמוד הליווי",
      kind: "text",
      max: 45,
      hint: "החץ ← חלק מהטקסט. היעד קבוע בקוד" }
  ],
};

export const HOME_PLAN: SectionType = {
  type: "home-plan",
  label: "התוכנית — סולם שלושת השלבים",
  purpose: "שלושת השלבים של הליווי, כסולם נגלל.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה",
      kind: "text",
      required: true,
      max: 40 },
    { key: "title",
      label: "כותרת הסקשן",
      kind: "textarea",
      required: true,
      max: 42 },
    { key: "titleAccent",
      label: "המילים עם הקו הוורוד",
      kind: "mark",
      of: "title",
      max: 18 },
    { key: "lead",
      label: "משפט מקדים",
      kind: "textarea",
      max: 130,
      hint: "max-w-[60ch]" },
    { key: "steps",
      label: "שלבי הליווי",
      kind: "repeater",
      required: true,
      itemLabel: "שלב",
      max: 3,
      fields: [
        { key: "n",
          label: "מספר",
          kind: "text",
          required: true,
          max: 2 },
        { key: "t",
          label: "שם השלב",
          kind: "text",
          required: true,
          max: 42 },
        { key: "d",
          label: "תיאור השלב",
          kind: "textarea",
          required: true,
          max: 520 }
      ],
      hint: "שלושה בדיוק — הסולם מעוצב לשלוש דרגות" },
    { key: "cta",
      label: "קישור להוכחה",
      kind: "text",
      max: 60 }
  ],
};

export const HOME_PROOF: SectionType = {
  type: "home-proof",
  label: "הוכחה — «היא באמת מבשלת»",
  purpose: "שלושה מתכונים אמיתיים מהארכיון, נבחרים אוטומטית בכל טעינה.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה",
      kind: "text",
      required: true,
      max: 40 },
    { key: "title",
      label: "כותרת הסקשן",
      kind: "textarea",
      required: true,
      max: 42 },
    { key: "titleAccent",
      label: "המילה עם הקו הוורוד",
      kind: "mark",
      of: "title",
      max: 18 },
    { key: "body",
      label: "משפט מקדים",
      kind: "textarea",
      max: 130 },
    { key: "countChip",
      label: "צ'יפ הכמות",
      kind: "text",
      max: 42,
      hint: "חייב להתאים למספר המתכונים האמיתי בארכיון" },
    { key: "darkTestimonial",
      label: "הערת ההמלצות",
      kind: "textarea",
      max: 160,
      hint: "מצב-ריק כן. לעדכן ביום שנכנסת המלצה ראשונה" },
    { key: "darkLogos",
      label: "הערת שיתופי הפעולה",
      kind: "textarea",
      max: 160 },
    { key: "cta",
      label: "קישור לכל המתכונים",
      kind: "text",
      max: 40 }
  ],
};

export const HOME_STAKES: SectionType = {
  type: "home-stakes",
  label: "הצומת — שתי הדרכים",
  purpose: "ההשוואה בין הדרך השקטה לשנה הרועשת, ואחריה פס הפעולה.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה",
      kind: "text",
      required: true,
      max: 40 },
    { key: "title",
      label: "כותרת הסקשן",
      kind: "textarea",
      required: true,
      max: 40 },
    { key: "titleAccent",
      label: "המילה עם הקו הוורוד",
      kind: "mark",
      of: "title",
      max: 18 },
    { key: "cue",
      label: "שורת ההמלצה",
      kind: "text",
      max: 40 },
    { key: "band",
      label: "משפט פס הסיום",
      kind: "textarea",
      required: true,
      max: 110 },
    { key: "bandCta",
      label: "כפתור הפס",
      kind: "text",
      required: true,
      max: 18,
      hint: "שורה אחת — הפינה החתוכה נשברת אחרת" },
    { key: "bandSecondary",
      label: "קישור משני בפס",
      kind: "text",
      max: 34 }
  ],
};

export const HOME_SUCCESS: SectionType = {
  type: "home-success",
  label: "השיא — «שעת הזהב»",
  purpose: "שלוש שורות של תחושה. אלה לא ציטוט ולא המלצה, ולעולם לא יסומנו ככאלה.",
  fields: [
    { key: "kicker",
      label: "שורת פתיחה",
      kind: "text",
      required: true,
      max: 40 },
    { key: "lines",
      label: "שלוש שורות ההרגשה",
      kind: "textarea",
      required: true,
      max: 92,
      lines: 3,
      maxPerLine: 45,
      hint: "שלוש שורות. כל שורה נחשפת בנפרד" },
    { key: "bridge",
      label: "כפתור המעבר לטופס",
      kind: "text",
      required: true,
      max: 32 }
  ],
};

export const HOME_CTA: SectionType = {
  type: "home-cta",
  label: "סגירה — הפאנל הנייבי",
  purpose: "הזמנה אחרונה לשיחה, מעל טופס יצירת הקשר.",
  fields: [
    { key: "title",
      label: "כותרת הסגירה",
      kind: "textarea",
      required: true,
      max: 50,
      lines: 2,
      maxPerLine: 25,
      hint: "שתי שורות" },
    { key: "body",
      label: "פסקת הסגירה",
      kind: "textarea",
      required: true,
      max: 190 },
    { key: "packages",
      label: "משפט החבילות",
      kind: "textarea",
      max: 190,
      hint: "בלי מחירים" },
    { key: "promise",
      label: "הבטחת המענה",
      kind: "text",
      required: true,
      max: 70,
      hint: "מספר ימי העסקים חייב להיות אמיתי" },
    { key: "trustToken",
      label: "תג האמון",
      kind: "text",
      required: true,
      max: 34 },
    { key: "trustTokenLicense",
      label: "סיפא הרישיון",
      kind: "text",
      max: 32,
      hint: "מוצג רק ממסך 640 ומעלה, ולכן מתחיל במפריד ‎ · ‎" }
  ],
};

export const REGISTRY: Record<string, SectionType> = Object.fromEntries(
  [
    HOME_HERO,
    HOME_FILM,
    HOME_GUIDE,
    HOME_PLAN,
    HOME_PROOF,
    HOME_STAKES,
    HOME_SUCCESS,
    HOME_CTA,
    TESTIMONIALS_HERO,
    TESTIMONIALS_GRID,
    TESTIMONIALS_CTA,
    CONTACT_DOOR,
    CONTACT_LEAD,
    CONTACT_WHERE,
    ABOUT_HERO,
    ABOUT_STORY,
    ABOUT_AGE,
    ABOUT_CREDENTIALS,
    ABOUT_PRESS,
    ABOUT_CTA,
    PAGE_META,
    COACHING_HERO,
    COACHING_PROBLEM,
    COACHING_METHOD,
    COACHING_PACKAGES,
    COACHING_PROCESS,
    COACHING_PROOF,
    COACHING_FAQ,
    COACHING_CTA
  ].map((s) => [s.type, s]),
);

export const getSectionType = (type: string): SectionType | undefined => REGISTRY[type];
