#!/usr/bin/env node
// 03-pages.mjs — the five page documents, as SQL.
//
// content/pages/*.json already has the exact shape of a `pages.sections` value,
// so this is a transcription and not a transformation. That is deliberate: the
// files were written in the database's shape from the first day precisely so
// that this step could be dull.
//
//   node scripts/migrate/03-pages.mjs
//
// Idempotent. The id is derived from the slug, so a re-run updates in place.
// baseline_order is written ONLY on insert: it records the order the site
// shipped with, and "restore the original order" would be worthless if a later
// seed re-pointed it at whatever the order happens to be now.

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { findUnterminatedString } from "../../src/lib/cms/recipe-migrate.mjs";
import { REGISTRY } from "../../src/lib/sections/registry.ts";

const ROOT = path.resolve(import.meta.dirname, "../..");
const SRC = path.join(ROOT, "content/pages");
const OUT = path.join(ROOT, "scripts/migrate/out");

const lit = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const jlit = (v) => `${lit(JSON.stringify(v))}::jsonb`;

const idFor = (slug) => {
  const h = createHash("sha256").update(`page:${slug}`).digest("hex");
  return [h.slice(0, 8), h.slice(8, 12), `5${h.slice(13, 16)}`, `8${h.slice(17, 20)}`, h.slice(20, 32)].join("-");
};

const files = readdirSync(SRC).filter((f) => f.endsWith(".json")).sort();
const docs = [];
const problems = [];

for (const file of files) {
  let doc;
  try {
    doc = JSON.parse(readFileSync(path.join(SRC, file), "utf8"));
  } catch (err) {
    problems.push(`${file}: could not be read or parsed — ${err.message}`);
    continue;
  }

  if (typeof doc.slug !== "string") problems.push(`${file}: missing slug`);
  if (!doc.title) problems.push(`${file}: missing title`);
  if (!Array.isArray(doc.sections)) problems.push(`${file}: sections is not an array`);

  // Every section must be modelled, or the desk shows a card it cannot open and
  // the seed stores a payload no form can ever reach.
  for (const s of doc.sections ?? []) {
    if (!REGISTRY[s.type]) problems.push(`${file}: section "${s.id}" has type "${s.type}" with no registry entry`);
    if (!s.id) problems.push(`${file}: a section is missing its id`);

    // AND every payload key must be declared. A key the registry misses is not
    // a formality: savePage refuses to publish such a section (it used to strip
    // the key — that is how a publish once deleted the stakes columns), so an
    // undeclared key here means a page that cannot be published from the desk.
    const reg = REGISTRY[s.type];
    if (reg) {
      const declared = new Set(reg.fields.map((f) => f.key));
      for (const k of Object.keys(s.payload ?? {})) {
        if (!declared.has(k)) problems.push(`${file}: ${s.type}.${k} exists in the payload but not in the registry`);
      }
      for (const f of reg.fields) {
        if (f.required && !(f.key in (s.payload ?? {}))) {
          problems.push(`${file}: ${s.type}.${f.key} is required by the registry but absent from the payload`);
        }
      }
    }
  }
  const ids = (doc.sections ?? []).map((s) => s.id);
  const dupes = ids.filter((x, i) => ids.indexOf(x) !== i);
  if (dupes.length) problems.push(`${file}: duplicate section ids — ${[...new Set(dupes)].join(", ")}`);

  docs.push({ file, doc });
}

const sql = [
  "-- seed-pages.sql — generated by scripts/migrate/03-pages.mjs. Do not edit by hand.",
  `-- ${docs.length} pages, ${docs.reduce((n, d) => n + d.doc.sections.length, 0)} sections.`,
  "--",
  "-- Transcribed from content/pages/*.json, which already carries the shape of a",
  "-- pages.sections value. Idempotent: the id is derived from the slug.",
  "--",
  "-- baseline_order is written ONLY on insert. It records the order the site",
  "-- shipped with, and the desk's «החזרת הסדר המקורי» button reads it — a later",
  "-- seed that re-pointed it at the current order would make that button a no-op",
  "-- exactly when it is needed.",
  "",
  "begin;",
  "",
  ...docs.map(({ doc }) => {
    const id = idFor(doc.slug);
    const kind = ["", "about", "coaching", "contact", "testimonials"].includes(doc.slug) ? "core" : "content";
    return (
      `insert into public.pages (id, slug, kind, title, description, sections, baseline_order, status, published_at)\n` +
      `values (${lit(id)}, ${lit(doc.slug)}, ${lit(kind)}::public.page_kind, ${lit(doc.title)}, ${lit(doc.description ?? null)},\n` +
      `        ${jlit(doc.sections.filter((s) => s.visible !== false))},\n` +
      `        ${jlit(doc.baseline_order ?? [])}, 'published', now())\n` +
      `on conflict (id) do update set\n` +
      `  title = excluded.title,\n` +
      `  description = excluded.description,\n` +
      `  sections = excluded.sections;`
    );
  }),
  "",
  "-- The FULL documents — hidden sections included — go to drafts, which has no",
  "-- anon policy at all. The pages rows above hold only the visible projection,",
  "-- so without these rows a section hidden at migration time would exist",
  "-- NOWHERE in the database, and the desk could never show or unhide it again.",
  "-- The desk reads drafts-first for exactly this reason.",
  ...docs.map(({ doc }) => {
    const id = idFor(doc.slug);
    return (
      `insert into public.drafts (entity_type, entity_id, payload)\n` +
      `values ('page', ${lit(id)}, ${jlit(doc)})\n` +
      `on conflict (entity_type, entity_id) do update set\n` +
      `  payload = excluded.payload,\n` +
      `  updated_at = now();`
    );
  }),
  "",
  "commit;",
  "",
].join("\n");

const bad = findUnterminatedString(sql);
if (bad !== null) {
  console.error(`generated SQL has an unterminated string literal, opened on line ${bad}`);
  process.exit(1);
}

mkdirSync(OUT, { recursive: true });
writeFileSync(path.join(OUT, "seed-pages.sql"), sql, "utf8");

for (const { file, doc } of docs) {
  console.log(`  ${file.padEnd(20)} ${String(doc.sections.length).padStart(2)} sections`);
}
console.log(`\n  wrote scripts/migrate/out/seed-pages.sql`);

if (problems.length) {
  console.error(`\n  ${problems.length} PROBLEM(S):`);
  for (const p of problems) console.error(`   - ${p}`);
  process.exit(1);
}
